snyk/kubernetes-monitor

src/transmitter/index.ts
test/system/kind.test.ts

when failing to transmit data to the Kubernetes-Upstream service, if the failure is a result of specific network errors, retry a certain amount of times.
otherwise, fail the request.
this is done because networks are often unpredictable and we see some socket hangups or unexpected network socket disconnections. in these scenarios we want to retry sending the request, so the important data isn't lost.
https://snyk.slack.com/archives/CFSQFR0TH/p1583315253000500

fix: retry transmissions on certain network failures

---

scripts/slack-notify-deploy.sh
scripts/slack-notify-failure.sh
scripts/slack-notify-push.sh
scripts/slack-notify-success-no-publish.sh
scripts/slack-notify-success-no-release.sh

To allow us to quickly infer if something went wrong (e.g. bright red on broken tests), improve the colors of the webhook (they used to be yellow for everything).
- [Examples on Slack #runtime-deployment](https://snyk.slack.com/archives/CLW30N31V/p1583420539002400)

chore: add colors to Slack webhook messages

---

test/setup/deployers/index.ts
test/setup/deployers/types.ts
test/setup/deployers/yaml.ts

Ensure that the different deployers export the deployer themselves, instead of individual functions.
The deployers are expected to stick to the interface, rather than having the index/entrypoint construct it for the consumers.
I would like us to have the individual deployers export an object that conforms to the IDeployer interface. So the `index.ts` just exports a simple collection of these different deployers.
Small refactor preceding the Operator tests we're about to add.

chore: rearrange the YAML deployer in tests

---

package-lock.json
package.json

the snyk-docker-plugin has released a new version with better key-binary scanning in terms of type validation between dynamic/static flows.
upgrading to make sure the new functionality is correct and fits the Monitor.
https://snyksec.atlassian.net/browse/RUN-761

fix: bump snyk-docker-plugin to a version with better key-binary scanning

---

scripts/publish-gh-pages.sh

Ensures that all the repo files are again available for subsequent CI job steps.
- Fixes #371 
- Tested manually by running the script

chore: restore to master branch after publishing to gh-pages

---

package.json

tap's default timeout for tests is 30 seconds.
our unit tests usually finish in about 29 seconds, but some times it crosses that limit, failing the run.
let's allow ourselves up to 5 minutes for unit tests to complete before failing builds.
https://snyk.slack.com/archives/CDSMEJ29E/p1583839235090400

chore: increase the timeout for unit tests to prevent flakiness

---

package-lock.json
package.json

Introduces a fix that allows errors to be emitted in Informer/Watch done() handlers.
This way we will be able to now see any API server errors, instead of receiving null in all cases.
- [The fix mentioned](https://github.com/kubernetes-client/javascript/commit/568a853dc10b41067f66e562853b2ca6d90d9c7b)
- [0.11.1 commits](https://github.com/kubernetes-client/javascript/commits/0.11.1)

fix: upgrade K8s client to capture errors in Watch done() handlers

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Presently there is no way to control the limits and requests the snyk-monitor deploys with, this simply enables that ability
Moves resource limits to values.yaml
Originally suggested by https://github.com/Joeskyyy in https://github.com/snyk/kubernetes-monitor/pull/381

feat: Add cpu and mem limits/requests to values.yaml

---

package-lock.json

removed node_modules and re-locked to upgrade dependencies. this got a newer version of minimist without the prototype pollution.
https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

fix: updating dependencies to fix vulnerability in minimist

---

package-lock.json
package.json
src/scanner/images/index.ts
src/scanner/types.ts
test/integration/kubernetes.test.ts
test/unit/scanner/images.test.ts

bump docker-plugin with Distroless scanning support
that's how I tested it locally:
1. build a local Distroless image
2. modify the system test to load it into the KinD cluster and run it
3. hack Skopeo's arguments during runtime so it doesn't try to save it from an image registry, but from my local docker daemon
4. observe the plugin scan the archive and return the same results as it does when running just the plugin on that image
I didn't enhance any of our tests since the logic of scanning Distroless belongs to the docker-plugin and not the Monitor. happy to enhance the testing in the Monitor if we think there's additional value in checking something specific.
https://snyksec.atlassian.net/browse/RUN-827

feat: docker-plugin with Distroless scanning support

---

test/integration/kubernetes.test.ts

single quotation marks instead of double

chore: single quotation marks instead of double

---

src/scanner/index.ts
src/supervisor/watchers/handlers/pod.ts
src/supervisor/watchers/handlers/workload.ts

The class was initially added to conceptually separate the scanning/processing logic from the rest of the code. This separation is in order to later transfer this piece of logic into a separate worker mechanism, e.g. a Kubernetes Job. This separation however never happened, and this is the only place in the code that uses a class but without an apparent reason.
Convert the class functions into plain async functions and export them in the scanner module.

fix: simplify scanner module by removing the usage of class

---

test/helpers/kubectl.ts
test/integration/kubernetes.test.ts

kubectl 1.18 deprecated creating deployments using the kubectl run command, so our checks no longer pass.
Adjust the tests to this new behaviour so that they now expect a Pod.
- [kubectl 1.18 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#kubectl)

chore: look for a Pod not a Deployment when using kubectl run in tests

---

package-lock.json
package.json
test/fixtures/binaries-deployment.yaml
test/integration/kubernetes.test.ts

The upgraded docker plugin supports scaccing openjdk hashes.
Bumping docker plugin version. The updated package supports openjdk binaries scanning, returning hashes in the pluginResult.

feat: upgraded docker plugin version

---

test/helpers/kubectl.ts

For OpenShift tests it may take a bit longer for the deployment to be created, so avoid flakiness by increasing the timeout.

chore: increase kubectl wait timeout in tests

---

.circleci/config.yml

Restore environment setup in EKS tests to fix test failures.
The CI job fails with an obscure error which seems like a bad interaction between the environment and pip.

chore: restore environment setup in EKS tests to fix test failures

---

Dockerfile
package-lock.json
package.json
src/scanner/images/index.ts
src/scanner/types.ts
test/unit/scanner/images.test.ts

Upgrade the snyk-docker-plugin dependency which carries @snyk/rpm-parser.
This allows us to scan RPM packages directly instead of shelling out to a tool.
We no longer need to pass a path to a temporary directory for storing extracted files.
Also, we no longer need to build and embed the tool in the Dockerfile.
If you see the following error:
```sh
npm ERR! code EEXIST
npm ERR! path /Users/ivan/repos/kubernetes-monitor/node_modules/@snyk/rpm-parser/node_modules/.bin/tsc
npm ERR! Refusing to delete /Users/ivan/repos/kubernetes-monitor/node_modules/@snyk/rpm-parser/node_modules/.bin/tsc: is outside /Users/ivan/repos/kubernetes-monitor/node_modules/@snyk/rpm-parser/node_modules/typescript and not a link
```
`rm -rf node_modules` and `npm i` will fix this!
- [Jira ticket …

feat: use a library to scan RPM packages instead of an external tool

---

scripts/slack/notify_deploy.py
scripts/slack/notify_failure.py
scripts/slack/notify_push.py
scripts/slack/notify_success_no_publish.py
scripts/slack/notify_success_no_release.py

For some reason passing `json` keyword into python `requests.post()` fails on some container configs, I'm expecting different python versions (?). As a solution, I'm passing `data` and parsing a dictionary into json with a lib.

fix: passing data keyword, instead of json, to requests.post()

---

.circleci/config.yml

To make sure we can always send slack notification in any failures we have to always install requests library, which is used to send the request when failed.
To make sure we can always send slack notification in any failures we have to always install requests library, which is used to send the request when failed.

chore: running install_python_requests always

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release-notes.yaml
test/integration/kubernetes.test.ts

bump release-notes-preview to require confirming the notes.
https://github.com/snyk/release-notes-preview/releases/tag/v1.5.0
before
after

chore: bump release-notes-preview to require confirming the notes

---

test/system/kind.test.ts

chore: fix bad name on type in kind.test.ts due to bad merge

---

.github/workflows/release-notes.yaml

It updates the Release-Notes-Pewview GitHub action to the latest version because it is currently not using the latest version and it should probably be using the latest version.
- [Jira ticket RUN-900](https://snyksec.atlassian.net/browse/RUN-900)

[RUN-900] chore: bump release-notes-preview GH action to 1.6.1

---

test/setup/platforms/kind.ts

Because the new nodejs version 12.16.3 created a issue with needle for request that need to be redirected. The test suites that need download KinD binary were breaking during the test. To workaround that we replaced the needle get request for a curl command.
The needle issue was reported [here](https://github.com/tomas/needle/issues/312).

chore: replace needle get request for curl on kind setup

---

scripts/publish-gh-pages.sh
test/fixtures/binaries-deployment.yaml
test/integration/kubernetes.test.ts

since the repository is now open-source the READMEs in develop should be enough.
no reason to refer anyone to the gh-pages branch for docs
stpp publishing the READMEs to gh-pages
- [Jira ticket RUN-903](https://snyksec.atlassian.net/browse/RUN-903)

[RUN-903] chore: stop publishing the READMEs to gh-pages

---

src/supervisor/kuberenetes-api-wrappers.ts
src/supervisor/types.ts

It has a small refactoring that moves the conditions that decides if k8s-monitor should or not retry a request using kubernetes API. It'll help include new logics that allow k8s-monitor retry for other errors.
It's first step before include retry policies for errors in this ticket [RUN-818](https://snyksec.atlassian.net/browse/RUN-818).

chore: extract the condition for retry request to the new function

---

README.md
snyk-monitor-deployment.yaml
snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
src/scanner/images/skopeo.ts
test/unit/scanner/skopeo.test.ts

Adds support in injecting SSL certs to skopeo copy for onprem registries
Tested manually.
* Modified our dockerfile and added `RUN rm -rf /etc/ssl/cert.pem` which caused:
```
{"name":"kubernetes-monitor","hostname":"snyk-monitor-6987fc6b67-2prkg","pid":51,"level":40,"message":"time=\"2020-05-10T11:57:05Z\" level=fatal msg=\"Error initializing source docker://rancher/local-path-provisioner:v0.0.11: pinging docker registry returned: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority\"\n","bin":"skopeo","loggableArguments":["copy","docker://rancher/local-path-provisioner:v0.0.11","docker-archive:/var/tmp/rancher_local_path_provisioner_v0_0_11_55801_148479917.tar"],"msg":"child process failure","time":"2020-05-10T11:57:05.149Z","v":0}
```
* got myself an …

[RUN-848] Feat/add ssl certs

---

src/supervisor/watchers/handlers/cron-job.ts
src/supervisor/watchers/handlers/daemon-set.ts
src/supervisor/watchers/handlers/deployment.ts
src/supervisor/watchers/handlers/job.ts
src/supervisor/watchers/handlers/replica-set.ts
src/supervisor/watchers/handlers/replication-controller.ts
src/supervisor/watchers/handlers/stateful-set.ts
src/supervisor/workload-reader.ts

Address TODO comments, either removing it or improve code, once it was clear which action we should take about each one.
Basically the TODOs are in two kinds of functions, the handlers and the readers.
For the handlers, we think it's ok we just remove the TODO and do nothing, we're already doing it in other handlers, and these handlers basically remove the workload from Homebase once it is removed from the cluster. If we have any problem, this workload would be removed from Homebase in 4 days anyway.
For the readers, it is worth including an info log with the workload name and namespace. Just because, in the future, if a customer has any problem, we will have some logs that will help us to investigate it.
- [Jira ticket RUN-545](https://snyksec.atlassian.net/browse/RUN-545)

fix: address TODO comments

---

Dockerfile
README.md
snyk-monitor-deployment.yaml
snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

We're adding support for insecure registries or using unqualified images in scanned containers.
To achieve that we've implemented support for `registries.conf` file, which is a system-wide configuration file for container image registries. The file format is TOML. 
For more information on how to format and examples: https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md
There is two commits, the first one is mounting `registries.conf` and the second one is updating docs.
- [Jira ticket RUN-965](https://snyksec.atlassian.net/browse/RUN-965)

[RUN-965] Feat/add registries conf to kubernetes-monitor installation

---

package-lock.json
package.json

needle has a bug with sockets on newer node 12,
we're currently avoiding this newer node 12 to
evade the problem. This bug is fixed in needle
2.5.0, so let's upgrade to that.
https://github.com/tomas/needle/issues/312

feat: upgrade needle (redirect bug)

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml
.circleci/config/jobs/push_operator_to_community_operators.yml

Avoid testing Operator upgrades and pushing to a branch in https://github.com/snyk/community-operators if no new version was released.
- [Jira ticket RUN-989](https://snyksec.atlassian.net/browse/RUN-989)

chore: skip Operator upgrade tests if no new version can be published

---

test/setup/index.ts
test/setup/platforms/index.ts
test/setup/platforms/kind.ts
test/setup/platforms/openshift3.ts

Pinning KinD binary version to 0.7.0, compatible with Kubernetes v1.11. We're using that specific version to mimic an OS3 cluster in our integration tests.

    fix: Pinning KinD version to 0.7.0 for OS3 tests

---

.circleci/config.yml
.circleci/config/@config.yml

The nightly job currently runs at midnight, which may collide with the periodic cluster restarting that we do for OpenShift (it happens once every 4 hours) and may explain occassional flakiness of the tests.
Push the tests to an hour that may not collide.
- [Slack discussion](https://snyk.slack.com/archives/CLW30N31V/p1595227713004000)

chore: run nightly jobs at 1AM to avoid clashes with cluster restart

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml

This is a temporary fix to help reduce flakiness. Sometimes this sleep amount is enough but in others the cluster is working a bit slower and causes the test to fail.
This is a debt that we should address in a better way in the future!
- [Slack thread](https://snyk.slack.com/archives/CLW30N31V/p1595984555016700)

chore: increase sleep timeout in Operator tests

---

Dockerfile

The .config directory in the product is shared between several entities:
- snyk protect creates it as part of storing metadata
- we mount registries.conf to override some image pulling properties
On OpenShift the mounting over an existing directory acts weird and makes the .config directory completely inaccessible to our user and breaking the registries.conf support that we have.
This fix pre-creates the directory with the right permissions in the Dockerfile so the OpenShift 3 behaviour is fixed.
- [Slack thread](https://snyk.slack.com/archives/CDSMEJ29E/p1596116581242200)

fix: fix permissions for registries.conf file in OpenShift 3

---

src/scanner/images/index.ts
test/unit/scanner/images.test.ts

before this fixes image names we show in the UI will chop everything after the first dash

fix: identify correclty image names that contains dashes

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
test/integration/kubernetes.test.ts
test/setup/deployers/helm-with-proxy.ts
test/setup/deployers/helm.ts
test/unit/deployment-files.test.ts

Allow to specify the nodeSelector fields in the Helm chart.
This solves https://github.com/snyk/kubernetes-monitor/issues/531 and is a contribution by @adhodgson1 originally at https://github.com/snyk/kubernetes-monitor/pull/532
- [RUN-1107](https://snyksec.atlassian.net/browse/RUN-1107)

[RUN-1107] feat: Allow to specify the nodeSelector fields in the Helm chart

---

test/setup/platforms/index.ts

It missed a rebase and because of that it got a miss match in a new function to platform test configuration interface.
Look at the KindOLM platform interface. It was missing the new interface method validateRequiredEnvironment that checks if the Env Var to access external clusters are available. For Kind OLM we don't need Env Var and we can just resolve it.

test: fix platform test configuration that was not following interface

---

Dockerfile

Included a few labels and a license folder in the Dockerfile.
It's related to the Operator certification process. We got a **PASSED** status on the image scan. Once it's merged, we can do the same for the production image.
- [RUN-1120](https://snyksec.atlassian.net/browse/RUN-1120)

fix: improve image metadata information

---

scripts/operator/create-operator.sh
snyk-operator/build/Dockerfile

Included a few labels and a license folder in the Dockerfile.
It's related to the Operator certification process. We got a **PASSED** status on the image scan. Once it's merged, we can do the same for the production image.
- [Jira ticket RUN-1052](https://snyksec.atlassian.net/browse/RUN-1052)

fix: improve operator image metadata

---

.circleci/config.yml
.circleci/config/@config.yml

Change the crontab for the monthly job to **"0 5 3 * *"**, to avoid it conflicts with the nightly job.

chore: avoid job conflict between nightly and monthly jobs

---

snyk-operator/build/Dockerfile

This reverts commit 1a4ff32bf1026d80acfb3a1299571c043fb34174, reversing
changes made to bba76d57a6674621f9aeaf91518ad55d57b4f536.
The base image introduces a breaking change and makes the Operator not work any more.

fix: Revert Operator image upgrade to reduce vulnerabilities

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
scripts/operator/create_operator.py
scripts/operator/create_operator_and_push.py
scripts/operator/delete_operators_from_quay.py
scripts/operator/download_operator_sdk.py
scripts/operator/get_last_published_operator_version.py
scripts/operator/get_quay_token.py
scripts/operator/main.py
scripts/operator/package_operator_bundle.py
scripts/operator/raise_pr_to_community_operators_from_our_fork.py
scripts/operator/upload_operator_bundle_to_quay.py
scripts/test-openshift4.sh

On some CircleCI jobs the python executable resolves to "/opt/circleci/.pyenv/shims/python3" which causes errors with our scripts. Make sure we always run the /usr/bin/python3 version.
- [CircleCI run](https://app.circleci.com/pipelines/github/snyk/kubernetes-monitor/2291/workflows/a4254f9d-4f3c-4adf-bb98-cae7acfecfd5)

chore: pin python executable in CI/CD

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
test/system/kind.test.ts

Use Ubuntu 2004 to make use of latest packages (e.g. more modern Python3).

chore: use Ubuntu 2004 for CircleCI machines to use latest pkgs

---

.circleci/config.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml

Pass credentials when deleting Operator from Quay, this was forgotten and was causing the CircleCI job to fail even on successful tests.

chore: pass credentials when deleting operator from quay

---

scripts/test-openshift4.sh

This is a mistake that ensures Operators can never be deployed.

chore: do not delete Quay Operators before CI tests start

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml

The recent 17.2.3 release has a bug and cannot process credentials with symbols like ( or * and breaks our builds. Pin to an earlier version just to unblock the pipeline.
- [Slack thread](https://snyk.slack.com/archives/CLW30N31V/p1605775915070700)

chore: pin semantic-release to unblock releases

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml

The missing closing brace `)` was causing CI failures

chore: add missing closing brace to script and add quotes around params

---

package.json

`test:integration` was missing; this redirects it to most useful fast integration test for convenience of testing via `npm t`. This is a benefit to local dev, since `npm t` isn't currently used in CI

chore: add missing npm script to fix `npm t`

---

snyk-monitor/README.md

In v3.4, --generate-name is a valid flag for `helm install` but not for `helm upgrade --install`. Running the v2 version of the command, as in the previous paragraph, still seems to work in v3.

docs: Remove invalid command

---

snyk-monitor/README.md

If any older version of the snyk helm repo is already present on the local machine, the current `helm repo add` command will not modify it, meaning the subsequent call to `helm upgrade --install` will use the latest _local_ chart, which may not be the latest _actual_ release. Adding `--force-update` as per this PR will ensure that the local repo is updated to include the latest actual release.

docs: Update helm installation command

---

README.md
package-lock.json
package.json
snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
snyk-monitor/templates/pvc.yaml
snyk-monitor/values.yaml
src/index.ts
test/system/kind.test.ts

[RUN-1250] Update helm templates to allow for a `pvc` value. When set, this replaces emptyDir with a PVC, backed by a PV whose provsiioning is handled separately
Allows users to store temporary files in custom storage via a PVC, rather than needing an empty node.
see slack channel # run-1250-demo
[RUN-1250]
see slack channel # run-1250-demo
[RUN-1250]: https://snyksec.atlassian.net/browse/RUN-1250
[RUN-1250]: https://snyksec.atlassian.net/browse/RUN-1250

feat:support storage in PVC

---

snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snyk-operator.v0.0.0.clusterserviceversion.yaml
snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snykmonitors.charts.helm.k8s.io.crd.yaml
test/fixtures/operator/custom-resource-k8s.yaml
test/fixtures/operator/custom-resource.yaml

feat: Add OpenShift configuration for supporting PVC storage
This was previously exposed via Helm, now making it available for the Operator installation as well.
This change allows both the PVC storage to be enabled and the initContainer image to be configured.

feat: Add OpenShift configuration for supporting PVC storage

---

.circleci/config.yml
.circleci/config/commands/install_helm.yml
.circleci/config/jobs/@jobs.yml
scripts/publish-gh-pages.sh

Install Helm during the release process and stop being dependant on a very outdated version of helm that was mysteriously living in `gh-pages` branch as a committed to SCM binary

chore: install helm from package manager

---

scripts/publish-gh-pages.sh

Remove call to Helm's deprecated `init` API

chore: remove call to Helm's deprecated `init` API

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
src/common/config.ts
src/supervisor/watchers/index.ts

Skip k8s jobs processing behind FF for debug purpose

fix: skip k8s jobs processing behind FF for debug purpose

---

snyk-monitor/templates/pvc.yaml
snyk-monitor/values.yaml
snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snyk-operator.v0.0.0.clusterserviceversion.yaml
snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snykmonitors.charts.helm.k8s.io.crd.yaml

For some users it is important to be able to configure the StorageClass of the PersistentVolumeClaim, as the default is not always the preferred option.
- [Jira ticket RUN-1377](https://snyksec.atlassian.net/browse/RUN-1377)

feat: allow configuring PVC StorageClass name

---

snyk-monitor/templates/deployment.yaml

adds quotes for the `.Values.skip_k8s_jobs` to avoid yaml `true`. 
Adds option for `tolerations` to handle preemtible nodes.

feat: add quotes for .Values.skip_k8s_jobs, add tolerations

---

.circleci/config.yml
.circleci/config/@config.yml
.circleci/config/jobs/@jobs.yml

Right now both the Operator on OpenShift and Operator on OLM tests depend on the same Operator being pushed to our Quay repository. Unfortunately the OpenShift tests delete the Operators from Quay once the test finishes, which interferes with the other test.
This ensures that the Operators are deleted only after both tests that depend on it complete.

chore: delete Operators from Quay after tests complete

---

src/supervisor/watchers/handlers/index.ts
src/supervisor/watchers/index.ts
src/supervisor/watchers/types.ts

Restart k8s informers on error event (e.g idle connection)

feat: restart k8s informers on error event (e.g idle connection)

---

test/helpers/exec.ts
test/helpers/kubectl.ts
test/integration/kubernetes.spec.ts
test/setup/deployers/helm-with-proxy.ts
test/setup/deployers/helm.ts
test/setup/index.ts
test/setup/platforms/eks.ts
test/setup/platforms/kind.ts
test/setup/platforms/openshift4.ts
test/system/kind.spec.ts

It seems like there is an issue with Jest where changes to process.env are not persisted through calls to child_process.exec(). This causes env vars like KUBECONFIG to be lost and to fail our tests. For now use a wrapper to explicitly pass process.env as a workaround.
- [Investigation notes](https://snyk.slack.com/archives/CLW30N31V/p1612860708027800?thread_ts=1612856703.026500&cid=CLW30N31V)

chore: pass process.env when calling child_process.exec()

---

src/supervisor/watchers/handlers/pod.ts

This solves the case where a workload is added, deleted, and then added again. Snyk-monitor thinks the image for this workload has already been scanned (because we cache this internally by name), however, this is a completely new workload and needs to be re-scanned so the generated Project can be visible for import in Snyk. So use uid in the caching key instead of name, which ensures a completely new instance of the new workload will result in a new cache key.
- [Slack thread](https://snyk.slack.com/archives/C85H8Q12Q/p1612381109115500)

fix: cache workloads using uid instead of name as caching key

---

snyk-monitor/templates/pvc.yaml
snyk-monitor/values.yaml

fix: helm upgrade failed with pvc.enabled but without pvc.storageClassName
related to Issue: #667 
to test locally:
```bash
export ClusterName=my-kubernetes-cluster
helm upgrade -i --namespace snyk-monitor snyk-monitor snyk-charts/snyk-monitor --set clusterName="$ClusterName" --set pvc.enabled=true
helm upgrade -i --namespace snyk-monitor snyk-monitor snyk-charts/snyk-monitor --set clusterName="$ClusterName" --set pvc.enabled=true
```
without this fix, you will face with error:
```bash
```
after this change all should work fine
- #667
- https://github.com/helm/charts/issues/20389#issuecomment-583854511

fix: helm upgrade failed with pvc.enabled

---

package.json
snyk-monitor-deployment.yaml
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
src/common/policy.ts
src/index.ts
src/transmitter/index.ts
src/transmitter/payload.ts
src/transmitter/types.ts
test/fixtures/workload-auto-import.rego
test/system/kind.spec.ts

The Rego rules are loaded by snyk-monitor at the start of the application, the rules are verified, and finally they are transmitted to upstream.
We want the rules to be compiled and processed client-side but any choice whether workloads should be imported or deleted happens in the upstream.
Test coverage provided in system tests to ensure the policy is being transmitted first thing on start up of the application.
Not updating the docs yet since the feature is not ready to be used (needs backend support).
- [Jira ticket RUN-1404](https://snyksec.atlassian.net/browse/RUN-1404)

feat: load user-defined Rego rules for workload auto-import

---

package-lock.json
package.json

For docker archives we extract auto detected user instructions from the image config. Some of the entries are missing "created_by" so we were throwing an error.

fix: Added filtering history entries with no "created_by"

---

snyk-monitor-deployment.yaml
snyk-monitor/templates/deployment.yaml
src/common/config.ts
src/common/policy.ts
test/integration/kubernetes.spec.ts
test/system/kind.spec.ts

The Rego policy was mounted in the same location as the image temporary storage. Snyk Monitor tries to clean up this directory on start up (for the case where we get storage mounted with a bunch of extra files in it), so it also tried to delete the policies location. This resulted in an error and is also a mistake.
Swap the location from /var/tmp to /tmp.

fix: load Rego policy from a different location

---

src/supervisor/watchers/handlers/pod.ts

This is mostly used for diagnostic purposes, we are normally not interested in this message and it pollutes the logs.

fix: use debug level when logging queue size

---

snyk-monitor-deployment.yaml
snyk-monitor/values.yaml

Based on some prior research in https://github.com/snyk/ops/commit/66686e7106f3d88fd8040a2b2fc6aad302c84b8e we believe some performance problems are caused by kubernetes limiting the CPU when Node.js needs more. The theory is because of GC. It's also possible because we shell out to other processes (skopeo). The snyk-monitor also runs as Burstable instead of Guaranteed.
Raising the limit doesn't affect kubernetes' placement rules, and (because cpu is inherently overcommittable) shouldn't cause any new exciting death cases.
- [Slack thread](https://snyk.slack.com/archives/CGSNWAE76/p1615363773057800)

fix: increase CPU limits from 1 to 2

---

package-lock.json
package.json

Update `@snyk/dep-graph` to 1.27.1 to remove lodash vulns
Same as https://github.com/snyk/kubernetes-monitor/pull/682, but contains `package.json` change

chore: update dep-graph lib to remove lodash vulns

---

package.json
scripts/local-testing.sh

Makes it easier to configure and launch snyk-monitor locally so that you can quickly deploy it for local testing.

chore: add a script to simplify setting up local testing

---

snyk-monitor/README.md
snyk-monitor/templates/pvc.yaml
snyk-monitor/values.yaml
snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snyk-operator.v0.0.0.clusterserviceversion.yaml
snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snykmonitors.charts.helm.k8s.io.crd.yaml
test/fixtures/operator/custom-resource-k8s.yaml
test/fixtures/operator/custom-resource.yaml
test/setup/deployers/helm.ts

This fixes a conflict where the PVC cannot be re-created because it already exists.
Add a flag `pvc.create` to control whether or not the PVC should be created or an existing one should be used.
```json
{
"level": "error",
"ts": 1617036694.7158043,
"logger": "controller-runtime.controller",
"msg": "Reconciler error",
"controller": "snykmonitor-controller",
"request": "snyk-monitor/snyk-monitor",
"error": "failed to get candidate release: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: PersistentVolumeClaim, namespace: snyk-monitor, name: snyk-monitor-pvc",
"stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal …
```

fix: introduce pvc.create flag in Helm chart

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml

Sometimes it takes the Operator a bit longer than the 2 mins timeout to deploy an upgrade to the snyk-monitor.

chore: increase Operator upgrade wait time to 5 mins and use polling

---

Dockerfile
package-lock.json
package.json
test/README.md
test/fixtures/alpine-pod.yaml
test/fixtures/binaries-deployment.yaml
test/fixtures/centos-deployment.yaml
test/fixtures/consul-deployment.yaml
test/fixtures/insecure-registries/push-dockerhub-image-to-local-registry.yaml
test/fixtures/java-deployment.yaml
test/fixtures/nginx-replicationcontroller.yaml
test/fixtures/proxying/tinyproxy-deployment.yaml
test/fixtures/redis-deployment.yaml
test/fixtures/scratch-deployment.yaml
test/helpers/kubectl.ts
test/setup/index.ts
test/setup/platforms/eks.ts
test/setup/platforms/index.ts
test/setup/platforms/kind-olm.ts
test/setup/platforms/kind.ts
test/setup/platforms/openshift3.ts
test/setup/platforms/openshift4.ts

This has been an outstanding issue for over a month, especially prevalent in AKS. After some inactivity in the cluster, the persistent connection to the K8s API server got interrupted and was never able to recover.
This new fix in the K8s client library puts a 30s keep alive to the Watch connection so that it does not get interrupted.
- [Jira ticket RUN-1441](https://snyksec.atlassian.net/browse/RUN-1441)
- https://github.com/kubernetes-client/javascript/pull/630
- https://github.com/kubernetes-client/javascript/issues/596
- https://github.com/kubernetes-client/javascript/issues/589

fix: upgrade K8s client library to add Keep Alive to watches

---

test/helpers/kubectl.ts

Previous change f6cd5964b94ed021c6887518ddd6a6e9b325cf03 removed the Pod generator from tests. However, generators in kubectl 1.11 (the OpenShift version) default to applying Deployments instead of Pods.
Restore the Pod generator only for OpenShift 3 tests.

chore: fix OpenShift 3 tests by using previously removed Pod generator

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml

Operator tests seem to fail and it's just a matter of increasing the timeout to give the OpenShift cluster enough time to resolve the changes. When debugging we can see that the new Pod is there but still initialising, so it needs more time to properly start.
```shell
$ kubectl get pod -n snyk-monitor
NAME                             READY   STATUS     RESTARTS   AGE
snyk-monitor-6c978fb849-6vk9j    0/1     Init:0/1   0          4m30s
snyk-monitor-fbb97cd7c-blwrj     1/1     Running    0          7m27s
snyk-operator-7b5459cdcb-l2mkg   1/1     Running    0          4m40s
```
```shell
$ kubectl describe catsrc snyk-operator -n openshift-marketplace
Name:         snyk-operator
Namespace:    openshift-marketplace
...
Image:         docker.io/snyk/kubernetes-operator-index:1.50.2
...
```

chore: fix operator upgrade test failures

---

.circleci/config.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
test/fixtures/operator/catalog-source-k8s.yaml
test/setup/deployers/operator-olm.ts
test/setup/platforms/kind-olm.ts

Update OLM to the latest version, which matches the one on OpenShift. This means the existing OperatorSource resource is deprecated, so we can now use CatalogSource instead, similarly to OpenShift.
Also align the CI/CD pipeline to the recent changes in OpenShift tests.
- [Jira ticket RUN-1490](https://snyksec.atlassian.net/browse/RUN-1490)

chore: fix Operator tests with OLM on vanilla Kubernetes

---

snyk-monitor/templates/deployment.yaml

Change the `initContainer` command to add "world" read/write permissions.

fix: add world read/write permissions to temp volume

---

.gitignore
src/scanner/images/index.ts
src/scanner/images/skopeo.ts
src/scanner/images/types.ts
test/fixtures/oci-dummy-pod.yaml
test/integration/kubernetes.spec.ts
test/unit/scanner/images.test.ts

Added fallback logic for pulling oci-archive image incase docker-archive image pull fails after x retries.

add support for pull oci images

---

test/setup/platforms/kind-olm.ts

The recent release of version 0.18.0 releases a breaking change and causes the setup of our OLM tests to fail.
For now instead of using the main branch, we pin to the non-breaking change release until we understand what we need to change in our test setup to accommodate the new version.

chore: pin Operator Lifecycle Manager to version 0.17.0

---

snyk-monitor/templates/serviceaccount.yaml
snyk-monitor/values.yaml
test/helpers/kubectl.ts
test/integration/kubernetes.spec.ts
test/setup/deployers/helm.ts

Allow passing arbitrary annotations to ServiceAccount with Helm.
Cherry-picked from https://github.com/snyk/kubernetes-monitor/pull/719, please see the original submission for the details!
- https://github.com/snyk/kubernetes-monitor/pull/719

feat: Allow passing arbitrary annotations to ServiceAccount with Helm

---

package-lock.json
package.json

Excluding `gradle/cache` paths when extracting `jar`s from images.

fix: exclude gradle/cache path when extracting jars

---

snyk-monitor/templates/deployment.yaml

Instead of using an `initContainer` we instad set the `fsGroup` within the pod `securityContext`. Kubernetes will **create** this supplimentary group and assign it to all processes running within the pod.
Fixes #739

fix: fixes #739 set securityContext.fsGroup at pod level

---

snyk-monitor/templates/deployment.yaml

This reverts commit be7c3e343da2b8e417e7eeabd44466787d5fc686, reversing
changes made to 24f49225aa72e60b48ef5bea6138cbe703517e4c.
OpenShift is unhappy about this change!

fix: revert mount permissions and init container

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml
snyk-monitor/templates/deployment.yaml

When using a PersistentVolumeClaim, it has a Volume attached to it that can be shared by Pods only on the same worker node.
On upgrades to the Deployment, Kubernetes assigns the new Pods to random Kubernetes worker nodes. If the new Pod is assigned to a different worker node, the PVC cannot be detached from the old Pod and assigned to the new Pod.
This is why when we use a PVC we now change the snyk-monitor Deployment strategy to Recreate. Kubernetes will first delete the old Pod, freeing up the PVC, which can then be used in the new Pod.

fix: use Recreate strategy for snyk-monitor when using PVC as storage

---

Dockerfile
README.md

Adds gcloud to the image. This to allow users to automatically access GCR images when their whole cluster runs on GKE.

[RUN-1516] Add gcloud

---

.github/PULL_REQUEST_TEMPLATE.md

Remove placeholders for internal link from github PR template

chore: remove placeholders for internal link from github PR template

---

snyk-monitor/README.md

Update the README with gcloud support added to dockercfg.

chore: update helm chart readme with gcloud

---

.dockerignore

Exclude files which are not needed from Docker by adding to .dockerignore.
Tidies up the Docker image by excluding files which are not needed by adding to .dockerignore.

[RUN-1515] Tidy up docker image

---

snyk-operator/build/Dockerfile

**Before:**
```shell
✗ High severity vulnerability found in openssl-libs
Description: RHSA-2021:1024
Info: https://snyk.io/vuln/SNYK-RHEL8-OPENSSLLIBS-1089748
Introduced through: openssl-libs@1:1.1.1g-12.el8_3
From: openssl-libs@1:1.1.1g-12.el8_3
Fixed in: 1:1.1.1g-15.el8_3
✗ High severity vulnerability found in nettle
Description: RHSA-2021:1206
Info: https://snyk.io/vuln/SNYK-RHEL8-NETTLE-1287634
Introduced through: nettle@3.4.1-2.el8
From: nettle@3.4.1-2.el8
Fixed in: 0:3.4.1-4.el8_3
✗ High severity vulnerability found in gnutls
Description: RHSA-2021:1206
Info: https://snyk.io/vuln/SNYK-RHEL8-GNUTLS-1287630
Introduced through: gnutls@3.6.14-7.el8_3
From: gnutls@3.6.14-7.el8_3
Fixed in: 0:3.6.14-8.el8_3
Tested 104 dependencies for known issues, found 3 issues.
```
**After:**
```shell
✓ …
```

fix: upgrade Helm Operator base image to resolve 3 high severity vulns

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Currently users can provide certificate files to be used to validate the TLS connection when pulling images from private container registries. However, these certificates are not used when doing HTTP requests to Kubernetes Upstream - the certs are used only for contacting the container registries.
If users provide a CA certificate under a configurable path (by default `/srv/app/certs/ca.pem`) then we can now use this cert to validate the chain of certs in the TLS connection to Kubernetes Upstream.
This is useful for on-prem customers that run their own copy of the Snyk infrastructure and provision their own certificates for TLS.
Manually tested 🙏 
I also considered automatically loading certificates from the `/srv/app/certs` directory, decoding the PEM to BER, and then using …

feat: allow setting and using NODE_EXTRA_CA_CERTS

---

snyk-monitor/templates/configmap.yaml
snyk-monitor/values.yaml

The workload auto-import and auto-delete policy now comes as a preset. In order to use it, users should provide a list of Snyk Organization public IDs so that snyk-monitor knows which Orgs to use for importing or deleting scanned images.

feat: Helm flag to set the Orgs to use for workload auto import/delete

---

.eslintrc.json
src/scanner/images/credentials.ts

Remove `new Buffer` usage, cos of security concerns

fix: remove Buffer constructor use for security reasons

---

snyk-monitor/README.md

Add info on `--reuse-values` option to README so users know they do not need to keep setting the values on every upgrade.

docs: add info on --reuse-values to README

---

snyk-monitor/README.md

The work for allowing customers to set custom CA certs was added previously and this PR adds info on how to do it to the READMEs.

docs: add setting custom CA certs to README

---

snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snyk-operator.v0.0.0.clusterserviceversion.yaml

Missed in the previous change. This allows the Operator to apply our Helm chart, which now contains a default NetworkPolicy.

fix: add permissions to the Operator to apply NetworkPolicies

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Allow setting annotations on the PodSpec of the snyk-monitor Deployment, which is useful for annotating it with AWS-specific data.
Cherry-picked from https://github.com/snyk/kubernetes-monitor/pull/793
Closes https://github.com/snyk/kubernetes-monitor/issues/765

feat: add metadata annotations for deployment

---

snyk-monitor/README.md

Having / in cluster name shows the cluster as empty in Snyk UI. Added note to README to advice users of this.

chore: Add clusterName advice to README

---

snyk-monitor/templates/configmap.yaml
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

To provide an option to pass an external ConfigMap containing workload policies. Currently it's not possible to provide a custom ConfigMap, as the default one is created and mounted by default. More info in https://github.com/snyk/kubernetes-monitor/issues/809
I decided introduce a slight change to the values.yaml interface regarding workload policies, but in terms of default behaviour, those changes don't change anything. The default policy will still be installed by default as it happens in the current version.
`workloadPoliciesMap` changes behaviour to represent an external ConfigMap name instead of the default map name.
I'm of course open for changes on the interface, but in my opinion this is the most flexible setup.
This change might affect documentation on: …

snyk-monitor: Add defaultWorkloadPolicies option

---

snyk-monitor/README.md
src/common/config.ts
test/common/config.spec.ts

Having `/ `in cluster name shows the cluster as empty in Snyk UI as the workloads fail to import. Any `/` in cluster names are now removed. The advice in the readme has been updated accordingly.

[RUN-1602] Remove slashes from cluster names

---

snyk-monitor/templates/configmap.yaml
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Fix `workloadPoliciesMap` references an external map 
Add `defaultWorkloadPoliciesMap` value to save the default map name

fix: workloadPoliciesMap references an external map

---

snyk-monitor/templates/psp.yaml

Allow `persistentVolumeClaim` in PodSecurityPolicy if PersistentVolumeClaim was selected to be used in `kubernetes-monitor`
Related to #739

fix: add pvc to allowed volumes in psp

---

src/state.ts
src/supervisor/watchers/index.ts
src/transmitter/payload.ts
src/transmitter/types.ts

Collecting the namespace metadata so that later we can use it for easy querying. Will be useful for the namespaced annotated import.

fix: internally track/cache watched namespaces

---

snyk-monitor/templates/deployment.yaml

Fix indentation for helm deployment.

fix: adjust yaml indetation for helm deployment

---

snyk-monitor/templates/_helpers.tpl
snyk-operator-certified/helm-charts/snyk-monitor/templates/_helpers.tpl

This ensures that customers can install multiple copies of snyk-monitor in their cluster.
We now ensure that all of the Helm resources have a name matching the Helm release name, which will be unique.
This allows global resources such as ClusterRoles to be unique.
https://snyk.zendesk.com/agent/tickets/12631

fix: ensure Helm releases have unique names for the resources

---

Dockerfile

The Anthos CLI is not used by snyk-monitor so it can be safely removed.
Reduces the image size by ~120 MB

fix: remove anthoscli from google cloud SDK reducing image size

---

.tool-versions

Move `.tool-versions`, presumably part of someone's local development workflow, over to node 14.

chore(tool-versions): node 14

---

config.default.json
src/supervisor/agent.ts
src/supervisor/kuberenetes-api-wrappers.ts
test/system/kind.spec.ts

Rather than retrying the request at most 3 times, and then simply setting the agentId to an automatically generated UUID, we instead keep retrying the request indefinitely until we're able to retrieve the Kubernetes Deployment ID.
The retry logic will backoff exponentially up to a maximum configured value in seconds.

fix: stabilise the monitor agent id

---

snyk-monitor/templates/configmap.yaml

Exclude Pod kind from auto events
This happens if Pods are running as a self-sufficient object.

fix: exclude Pod kind from auto events

---

src/supervisor/kuberenetes-api-wrappers.ts
test/system/kind.spec.ts

Currently this crashes the application when the API server interrupts the connection while listing namespaces.
Retrying now gives us the opportunity to recover. Since we retry only a few times, we could still eventually crash the app again. But now the app  is protected from temporary API server flakes.
https://snyk.slack.com/archives/CFSQFR0TH/p1629158892003300

fix: retry listing workloads when receiving ECONNRESET

---

src/supervisor/metadata-extractor.ts

When encountering a pod associated with an owner, but not finding its owner, it should suffice to log the pod's metadata so we know the name and ownerReference.
Logging the entire pod object could result in either accidentally leaking sensitive data, or just logging an unbounded huge object and break log parsing.
https://snyk.slack.com/archives/CGSNWAE76/p1629843908057000

fix: don't attempt to log an entire pod object

---

package-lock.json

update tar to remediate [SNYK-JS-TAR-1579147](https://snyk.io/vuln/SNYK-JS-TAR-1579147)
```
tar@6.1.0
node_modules/tar
tar@"^6.0.2" from @kubernetes/client-node@0.15.0
node_modules/@kubernetes/client-node
@kubernetes/client-node@"^0.15.0" from the root project
```

fix: update tar to remediate SNYK-JS-TAR-1579147

---

.circleci/config.yml
.circleci/config/@config.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
.circleci/config/jobs/operator_upgrade_tests.yml
.circleci/config/jobs/push_operator_to_community_operators.yml
.circleci/config/jobs/push_operator_to_embedded_community_operators.yml
.circleci/config/jobs/sync_embedded_community_operators_with_snyk_fork.yml
scripts/operator/get_last_published_operator_version.py
scripts/operator/pr_resources.py
scripts/operator/push-operator-to-snyk-upstream.sh
scripts/operator/raise_pr_to_embedded_community_operators_from_our_fork.py
scripts/slack/notify_success_operator_push.py

the operator repo has been split into 2 repos so now the operator needs published in 2 places, redhat-openshift-ecosystem/community-operators-prod and k8s-operatorhub/community-operators
The operator repo has been split into 2 repos so now the operator needs published in 2 places:
- redhat-openshift-ecosystem/community-operators-prod
- k8s-operatorhub/community-operators

[RUN-1671] Use the new operator repos

---

snyk-operator-certified/Dockerfile
snyk-operator-certified/bundle.Dockerfile
snyk-operator-certified/bundle/manifests/snyk-monitor.clusterserviceversion.yaml
snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snyk-operator.v0.0.0.clusterserviceversion.yaml

Kubernetes has been deprecating API(s) which will be removed and no longer available in 1.22 and in the Openshift version 4.9.
For now we disable upgrades until we resolve the deprecated APIs and upgrade them to supported versions. Without this change the current version of the Operator does not get approved to the Community Operators repo.
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/208#issuecomment-915354409

fix: the snyk-operator does not use OCP 4.9 due to deprecated APIs

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
test/setup/deployers/helm.ts

Resolves https://github.com/snyk/kubernetes-monitor/pull/871.
Added tests with Helm.

fix: allow configuring fsGroup and projected volumes for AWS EKS

---

snyk-monitor/README.md

document an alternative way to read a projected service account token

docs: alternative way to read a projected service account token

---

snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml

It comes as a feature request from a customer experiencing problem of deploying snyk-monitor due to not having enough ephemeral-storage in the pod resources. We want to make requests and limits configurable, so user can adjust the value as needed.
[Github Issue](https://github.com/snyk/kubernetes-monitor/issues/870)

fix: allow requests and limits to be configurable

---

.circleci/config.yml
.circleci/config/commands/install_helm.yml

Install via script (https://helm.sh/docs/intro/install/#from-script) instead of from 3rd party repo. This way we can ensure that the latest release is always picked and there are no issues with downloading it.

chore: install Helm from script instead of 3rd party repo

---

src/scanner/index.ts
src/supervisor/watchers/handlers/pod.ts
src/transmitter/payload.ts
src/transmitter/types.ts
test/system/kind.spec.ts
test/unit/transmitter-payload.spec.ts

We are looking to improve our process of scanning images. Right now we have no visibility into how long an average image scan takes. For this reason we collect the following timings: time spent in queue, time spent pulling images, time spent scanning images. Additionally, collect the current queue size at the start of the image scan.

[RUN-1850] feat: collect telemetry to understand time spent scanning images

---

src/common/config.ts
test/common/config.spec.ts

You can now set the environment variable SNYK_WORKLOADS_TO_SCAN_QUEUE_WORKER_COUNT to override the queue size.

fix: allow overriding queue size with environment variable

---

package-lock.json
package.json

Upgrade aws-sdk from 2.995.0 to 2.999.0

fix: upgrade aws-sdk from 2.995.0 to 2.999.0

---

src/scanner/index.ts
src/state.ts

The workload cache expires in one minute, which means that images that weren't scanned quickly enough were accidentally not transmitted to Snyk.
The check now ensures that it skips sending data only if both the workload and the image are missing.

fix: check image cache before skipping sending scan results

---

package-lock.json
package.json
tsconfig.json

Upgrade Kubernetes Monitor to use Node v16 TLS.

RUN-1914 fix: update to node v16

---

src/supervisor/watchers/handlers/cron-job.ts
src/supervisor/watchers/handlers/daemon-set.ts
src/supervisor/watchers/handlers/deployment-config.ts
src/supervisor/watchers/handlers/deployment.ts
src/supervisor/watchers/handlers/job.ts
src/supervisor/watchers/handlers/pagination.ts
src/supervisor/watchers/handlers/pod.ts
src/supervisor/watchers/handlers/replica-set.ts
src/supervisor/watchers/handlers/replication-controller.ts
src/supervisor/watchers/handlers/stateful-set.ts
src/supervisor/watchers/handlers/workload.ts
src/supervisor/workload-reader.ts

I noticed a few other places where the workload metadata is not trimmed.
In the logs you could still see "managedFields" appearing, which is a pretty large object in some cases.
This change now ensures that we trim the metadata everywhere we receive a workload.

fix: trim workload metadata everywhere we read workloads

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Signed-off-by: Valentin Maillot <valentin.maillot@adfinis.com>
This PR is adding the ability to add additionnal labels for the snyk-monitor pod deployment.
Just add some labels et try to render the chart with `helm template .`.

feat(snyk-monitor): add ability to configure additionnal labels

---

package-lock.json
package.json
src/supervisor/watchers/handlers/deployment-config.ts
src/supervisor/watchers/handlers/index.ts

Upgrading  @kubernetes/client-node-version to v0.16.1 seemed to stop Kubernetes Monitor from scanning. We are hoping reverting to v0.15.1 would fix the issue.
[slack thread](https://snyk.slack.com/archives/C01KWP7CKQC/p1640013904002500)

chore: revert @kubernetes/client-node to v0.15.1

---

snyk-monitor/values.yaml

It is missing in the file but is used in the Deployment template
Adds a missing value to `snyk-monitor` Helm chart so that people don't have to go search the repository to verify it is possible to set it
Tests are unnecessary since this has no effect on behavior and simply serves as documentation
Unnecessary

Add tolerations to values.yaml

---

snyk-monitor/templates/networkpolicy.yaml
snyk-monitor/values.yaml

Adds a flag to disable the default `NetworkPolicy`. Ref - https://github.com/snyk/kubernetes-monitor/issues/984

Flag to disable NetworkPolicy

---

src/supervisor/kuberenetes-api-wrappers.ts
src/supervisor/watchers/handlers/index.ts
src/supervisor/watchers/index.ts
src/supervisor/watchers/types.ts

Add several other errors to the list of retryable errors for when the informer faces a network issue. This should make reconnecting to the K8s API more robust as these network errors are normally only temporary.

fix: retry on network errors in K8s API informers

---

package-lock.json
package.json
src/scanner/images/index.ts
src/scanner/images/skopeo.ts
src/scanner/images/types.ts
src/scanner/index.ts
src/supervisor/watchers/handlers/index.ts
src/transmitter/types.ts
test/system/kind.spec.ts

For some image archives this results in much smaller pulled images as it allows to directly download compressed layers.
Also, it reduces the need to convert between different formats on the fly, which skopeo had to do for us.

fix: pull OCI archives instead of Docker archives

---

src/supervisor/types.ts
src/supervisor/watchers/handlers/cron-job.ts
src/supervisor/watchers/handlers/index.ts
src/supervisor/workload-reader.ts
test/fixtures/cronjob-v1beta1.yaml
test/fixtures/cronjob.yaml
test/helpers/kubectl.ts
test/integration/kubernetes.spec.ts
test/setup/platforms/kind.ts

The CronJob workload that snyk-monitor supports is the batch/v1beta1 API which has been around for a long time. Starting version 1.21 of Kubernetes this API has graduated and is now GA under batch/v1. This PR updates the monitor to use that version.

[RUN-1518] Add support for CronJobs in batch/v1 API

---

src/scanner/index.ts
src/supervisor/watchers/handlers/pod.ts

Small bugfix to how we track state. Previously we were not actually deleting keys from the cache at all. This could result in a race condition where we would still send scan results to the upstream even though the workload was already deleted.
We used to set the key in the cache by "image id" but try to delete by "image name"

fix: track image state to avoid sending data for deleted workloads

---

src/scanner/index.ts

The previous change introduced a regression - workload scan results are now rarely sent upstream.

fix: correctly track workload and image state

---

.circleci/config.yml
.circleci/config/jobs/build_and_upload_operator.yml
.circleci/config/jobs/build_image.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
.circleci/config/jobs/openshift4_integration_tests.yml
scripts/docker/approve-image.sh
scripts/operator/main.py

Trim Operator name in tests so it's within K8s name limits.
The limit is 63 characters and because we generate a SHA for the name, it exceeds the limit.

chore: trim Operator name in tests so it's within K8s name limits

---

src/scanner/index.ts
src/supervisor/watchers/handlers/pod.ts
test/unit/scanner/scan-results-caching.spec.ts

[RUN-2156] test: image and workload caching and queueing

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml

Operator upgrade tests are currently broken. This change reverts the changes in the "Upgrade Operator and check that snyk-monitor also upgraded" step and also checks for the operator tag without -ubi suffix

fix: operator upgrade tests

---

src/index.ts

According to Sysdig, the runtime packages info gets processed within 15 minutes.
Do initial scrape after 20 mins to get Sysdig data into Snyk system earlier.
Further scrapes will still have 4 hour interval.

[RUN-2210] Scrape for runtime data after 20 mins

---

src/supervisor/watchers/handlers/deployment-config.ts

Import and use the trimWorkload function which was previously not implemented for DeploymentConfig for delete requests.

[RUN-2214] trim DeploymentConfig on delete

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml

Skopeo was removed from the `kubic` repo, but is available from the official Ubuntu repo (from 20.10 and up). This caused the system checks to fail in CircleCI.
Upgrading the base image to Ubuntu 22.04 to fix skopeo install.

chore: fix skopeo install

---

package-lock.json
package.json

Bumping the plugin with support for RPM 4.16.
Stating from this version, rpm moved to use an SQLite DB instead of Berkley DB. 
Due to a limitation in the CLI, had to switch the library we use to read the DB from `sqlite` to `sql.js`

feat: support rpm>=4.16 container images

---

test/setup/platforms/openshift4.ts

Clean up namespaces after test

chore: clean up namespaces after test

---

package-lock.json
package.json

This dependency bump should fix the "Invalid version" error we're seeing when scanning some Python projects

fix: container python app scan errors

---

.circleci/config.yml
.circleci/config/@config.yml

We want to temporary pause the publish operator until we fix some of our tests.

chore: pause publish operator

---

.circleci/config.yml
.circleci/config/jobs/openshift4_integration_tests.yml
test/setup/deployers/operator-openshift.ts
test/setup/index.ts
test/setup/platforms/openshift4.ts

For some reason `kubectl wait --for=condition=available` does not work only in CircleCI and only for OpenShift tests, causing failures. Replacing this with a `sleep()` seems to fix it. I can't reproduce the problem locally and I'm out of ideas on how to fix it other than by sleep()-ing...

test: fix openshift4 flakes

---

src/transmitter/index.ts

According to the HTTP spec, DELETE requests cannot contain a body. This change ensures we now send data via query string.
- Existing integration test already covers the case where a workload is deleted and we observe the upstream no longer has this workload: test/integration/kubernetes.spec.ts:602: snyk-monitor sends deleted workload to kubernetes-upstream
- The test may fail until the upstream service deploys with the query string support - will rerun once deployed

fix: delete workload requests send data with query string

---

package-lock.json
package.json

Contains a fix for Go app vuln scanning, see [snyk/snyk-docker-plugin#461](https://github.com/snyk/snyk-docker-plugin/pull/461)

fix: bump snyk-docker-plugin

---

package-lock.json
package.json

fix: use full version of go modules in dep-graph
- https://github.com/snyk/snyk-docker-plugin/pull/462
- https://github.com/snyk/snyk-docker-plugin/releases/tag/v5.6.4

fix: update snyk-docker-plugin

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

initContainers required to be run as root to provision pvc for temporary storage. We want to allow it to be configured, so user has the option to choose on installation.

fix: allow init containers to be configured

---

snyk-monitor/values.yaml

This should put less strain on the CPU, reduce how many images we pull concurrently, therefore it should slightly improve performance and make individual image scanning faster.

fix: reduce worker count from 10 to 5

---

test/fixtures/private-registries/debian-deployment-gcr-io.yaml

RUN-2499 chore: fix debian GCR fixture that crashes in a loop

---

.circleci/config.yml
.circleci/config/@config.yml

Temporarily disable the tests until we have time to review the failures. The problem seems to be stemming from our integration cluster.

chore: disable flaky openshift tests

---

package-lock.json
package.json
src/scanner/images/index.ts
src/scanner/index.ts
test/system/kind.spec.ts
test/unit/scanner/images.spec.ts

Pass workload metadata image Id when available to Snyk Docker Plugin to collect image names as a new fact.

RUN-2459 feat: pass image id to snyk docker plugin 

---

Dockerfile
Dockerfile.ubi8
scripts/docker/build-image-ubi8.sh

This PR resolves vulns found in the kubermetes-monitor images (alpine and rhel-ubi):
1. vulns found in gcloud-sdk platform directory: https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-3112177, https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-3112180
2. vuln found in docker-credential-acr-env go binary: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515
3. vuln found in node16 version of the RHEL UBI image: https://security.snyk.io/vuln/SNYK-RHEL8-NODEJS-2430358 
For the vuln found in docker-credential-acr-env, there is already a PR to fix it in the original repo, but it's not merged yet, therefore it is currently being fixed manually: https://github.com/chrismellard/docker-credential-acr-env/pull/12

[CIT-76] fix: fix vulns in gcloud-sdk acr-env and node

---

.circleci/config.yml
.circleci/config/@config.yml
test/integration/kubernetes.spec.ts

Attempt to fix `eks` and `aks` integration test, we pinned the Argo Rollout version in the test to an earlier version due to a [bug](https://github.com/argoproj/argo-rollouts/issues/2568)

[CIT-76] chore: use different argo rollout version for testing

---

test/fixtures/operator/custom-resource-k8s.yaml
test/fixtures/operator/custom-resource.yaml
test/integration/kubernetes.spec.ts
test/setup/deployers/helm-with-proxy.ts
test/setup/deployers/helm.ts
test/setup/deployers/operator-olm.ts
test/setup/deployers/operator-openshift.ts
test/setup/deployers/types.ts
test/setup/deployers/yaml.ts
test/setup/index.ts

This PR sets a unique cluster name for each integration test run.
This is done as a preliminary step for a future change, where we will use the same integration ID in all integration tests. This change would ensure that in the future change, the tests will not affect each other.

[CIT-75] test: use unique cluster name in integration tests

---

scripts/circleci-jobs/deploy_to_dev.sh

add snyk log labels and annotation values placeholders in deploy_to_dev script to allow controlling snyk logs destinations.

chore: add snyk log labels values in deploy to dev

---

snyk-monitor/templates/deployment.yaml

Adds new optional env var `SNYK_SERVICE_ACCOUNT_API_TOKEN` to helm chart.

[CIT-75] Add optional service acc token env var

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
snyk-operator-certified/helm-charts/snyk-monitor/templates/deployment.yaml
snyk-operator-certified/helm-charts/snyk-monitor/values.yaml

This PR allows `snyk-monitor` to run on arm64 systems, for example MacOS M1

allow snyk-monitor to run on arm64

---

src/transmitter/index.ts
test/unit/transmitter-retry.spec.ts

Updates retry logic from:
| Condition  | Behaviour                 |
| ---------- | ------------------------- |
| 502        | 3 attempts, 2 second wait |
| ECONNRESET | 3 attempts, 2 second wait |
| EAI_AGAIN  | 3 attempts, 2 second wait |
to:
| Condition  | Behaviour                 |
| ---------- | ------------------------- |
| 429        | 3 attempts, 1 minute wait |
| 502        | 3 attempts, 2 second wait |
| 503        | 3 attempts, 2 second wait |
| 504        | 3 attempts, 2 second wait |
| ECONNRESET | 3 attempts, 2 second wait |
| EAI_AGAIN  | 3 attempts, 2 second wait |

feat: retry transmitting data to upstream on known http errors

---

Dockerfile
Dockerfile.ubi8

go install latest docker-credential-acr-env in image
Previous version of docker-credential-acr-env had vulnerable dependencies which were solved in the latest version. Therefore we can now use the latest version in our image. Using a pinned version in case 'latest' tag has a breaking change.

chore: go install latest docker-credential-acr-env

---

snyk-operator-certified/Dockerfile
snyk-operator/build/Dockerfile

Updates helm operator version
Resolved:
- https://security.snyk.io/vuln/SNYK-RHEL8-LIBKSBA-3232176
- https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2HPACK-3358253
- https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-3323837
Waiting on upstream to resolve existing:
- https://security.snyk.io/vuln/SNYK-RHEL8-OPENSSLLIBS-3315644
- https://quay.io/repository/operator-framework/helm-operator?tab=tags

chore: update helm operator version

---

Dockerfile
Dockerfile.ubi8

Upgrade docker-credential-acr-env to allow OIDC authentication via Azure Workload Identity.
Issue: https://github.com/snyk/kubernetes-monitor/issues/1223
Closes this PR: https://github.com/snyk/kubernetes-monitor/pull/1283

feat: allow OIDC authentication via Azure Workload Identity

---

.github/workflows/relock.yaml

Use staging branch for npm relock workflow.
NPM relock jobs fail today on the step to checkout code from `main` branch, which does not exist. For example: https://github.com/snyk/kubernetes-monitor/actions/runs/4843210077/jobs/8630653941

chore: use staging branch for npm relock

---

snyk-monitor/templates/deployment.yaml
snyk-operator-certified/helm-charts/snyk-monitor/templates/deployment.yaml

The current Kubernetes helm chart assumes that the value of kubernetesIoArch is set. If the parameter is not set, the creation of the helm chart fails with `Required value: must be specified when operatoris 'In' or 'NotIn'`
Fixes https://github.com/snyk/kubernetes-monitor/issues/1277
To reproduce the issue, you need to delete the following lines: https://github.com/snyk/kubernetes-monitor/blob/staging/snyk-monitor/values.yaml#L105-L106

fix: helm chart when kubernetesIoArch value is missing

---

test/README.md

Remove unused env var from README

chore: remove unused env var from README

---

.circleci/config.yml

Use custom circleci context instead of nodejs-app-release-public context.

chore: replace circleCi context

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
test/integration/kubernetes.spec.ts

We build the snyk-monitor image only for the linux/amd64 platform.
This change ensures we are scheduling the app only on worker nodes of that type.
Before this change, the app could've been scheduled on Windows worker nodes, which wouldn't work as we have no Windows variant of the snyk-monitor

feat: schedule the snyk-monitor on linux worker nodes

---

.circleci/config.yml
.circleci/config/@config.yml
snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Add envvar AZURE_CLIENT_ID that allows specifying a managed identity to be used when pulling images for scanning.
Updated Helm chart to add AZURE_CLIENT_ID envvar to `snyk-monitor` container, when needed (not empty string). The envvar is needed to avoid conflicting managed identities that allow the `snyk-monitor` to pull images from the container registry, therefore explicitly saying which of the identities to be used (by specifying its Client ID). 
Will update documentation about setting up `kubernetes-monitor` in Azure.
N/A

fix: add envvar AZURE_CLIENT_ID option

---

test/fixtures/sidecar-containers/deployment.yaml

The extensions/v1beta1 would be deprecated after k8s v1.22
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122 
We want to update this to prevent having flaky tests in the future.

chore: upgrade deprecated k8s api for fixture

---

Dockerfile.ubi9
scripts/docker/build-image-ubi9.sh
scripts/docker/build-image.sh
scripts/docker/smoke-test-image-binaries.sh

This PR improves the installation and verification of dependencies in the UBI9 image build.
Dependency installation via package managers or builds from source have been replaced by binary downloads. Binaries are downloaded with `curl`s `-f (--fail)` set, and hashes of the downloaded files are checked before continuing the build. A notable exception is `gcloud`, the Google Cloud CLI, which continues to be installed via their provided script. Python 3 is no longer explicitly installed, and instead we allow `gcloud` to install its bundled version of Python.
The application is now built using the `ubi8/nodejs-16` base image, to align more closely with the production container's base image. Due to the age of Node.js 16, a UBI9 base image is not available. When this project updates to use …

fix: UBI9 image build

---

snyk-monitor/values.yaml

Closes #1341.
Deprecated since v1.14: https://github.com/kubernetes/kubernetes/pull/108554/files#diff-2ae36f29c051a5b09a934647b62e2374b20d8048a6e2b80d03871e4f7c0d4b5aR29-R30

chore: set disableBetaArchNodeSelector to true

---

package-lock.json
package.json

This PR updates the version of the snyk-docker-plugin dependency.
The snyk-docker-plugin did not handle correctly in the previous version the case when the docker daemon is unavailable, and both the image digest and tag are passed as arguments. The bug is fixed in the new version.
Snyk-docker-plugin PR: https://github.com/snyk/snyk-docker-plugin/pull/527

fix: bump snyk-docker-plugin version

---

src/supervisor/watchers/handlers/cron-job.ts
src/supervisor/watchers/handlers/index.ts

- (to be manually tested) Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
This PR implements an adjustment to the checks for supported Kubernetes Batch API versions. If request is made to determine whether the deprecated `batch/v1beta1` API is supported, support for `batch/v1` will be first be checked, and if found, the response will indicated `batch/v1beta1` is not supported. This avoids making any calls to `batch/v1beta1` API endpoints if `batch/v1` is supported.
This needs to be manually tested before it can be merged! As a team, @snyk/container-integration made the decision that it's not worth implementing a suite of automated tests to check this behaviour - because K8s v3 will be out soon, and the time is better spent there.

[SUP-1884][SUP-1973] fix: avoid calling deprecated batch apis

---

src/index.ts
src/supervisor/watchers/handlers/argo-rollout.ts
src/supervisor/watchers/handlers/types.ts
src/supervisor/workload-reader.ts
test/fixtures/argo-rollout.yaml
test/integration/kubernetes.spec.ts
test/unit/supervisor/workload-reader.spec.ts

Argo Rollouts support defining pod templates directly within a rollout or by referencing a separate Deployment, ReplicaSet, or PodTemplate resource. Currently, if the template is not directly defined, a TypeError is raised:
```
{
"name": "kubernetes-monitor",
"hostname": "snyk-monitor-84f889474c-6vlkv",
"pid": 31,
"level": 50,
"error": {
"message": "Cannot read properties of undefined (reading 'metadata')",
"name": "TypeError",
"stack": "TypeError: Cannot read properties of undefined (reading 'metadata')\n    at argoRolloutReader (/srv/app/src/supervisor/workload-reader.ts:355:28)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at findParentWorkload (/srv/app/src/supervisor/metadata-extractor.ts:100:32)\n    at …
```

fix: Add support for Argo Rollouts that use workloadRef definitions

---

.circleci/config.yml
src/data-scraper/index.ts
src/data-scraper/scraping-v1.ts
src/transmitter/payload.ts
test/unit/data-scraper/scrape-data.spec.ts

- (n/a) Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
This PR modifies the Sysdig (v1 and v2) integration to avoid sending runtime data payloads upstream when all runtime images have been filtered out - usually due to being in an ignored namespace.

fix: avoid sending empty runtime images payloads

---

Dockerfile.ubi9

- N/A Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- N/A Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
This PR aims to remove a high vuln in the ubi9 docker image introduced through the docker-credential-acr-env package that we install.
The `docker-credential-acr-env` repository is not maintained and does not make any new releases, even though a fix for this vuln has been merged into the repo. The solution implemented in this PR creates another step in the ubi9 Dockerfile where the binary is built from source using `go install` pointed at the latest commit (as of writing this).
[Jira ticket OI-183](https://snyksec.atlassian.net/browse/OI-183)

feat: build acr cred helper binary from source [OI-183]

---

Dockerfile

`anthoscli` is not there anymore and build was failing when trying to remove it. According to a previous commit, it was removed from the image because we weren't using it and it used ~120MB. Now it's not present anymore by default. I built the new image locally and there's no `anthoscli` (searched with `find` utility).

fix: don't remove anthoscli anymore

---

.circleci/config.yml

remove redundant snyk orb based security scanning now covered by prodsec/security_scans.

fix: remove redundant snyk scanning covered by prodsec/security_scans

---

src/supervisor/watchers/handlers/namespace.ts

Duplicate of #1506 
closes #1506
What this does
Fixes https://snyk.zendesk.com/agent/tickets/80279
The crux of the issue is this:
```bash
➜  kubernetes-monitor git:(master) ✗ kubectl get --raw "/api/v1/watch/namespaces/services" | jq .
{
// Irrelevant fields omitted, note the resourceVersion
"type": "ADDED",
"object": {
"kind": "Namespace",
"apiVersion": "v1",
"metadata": {
"resourceVersion": "616",
},
}
```
```bash
➜  kubernetes-monitor git:(master) ✗ kubectl get --raw "/api/v1/watch/namespaces/services?resourceVersion=616" | jq .
{
"type": "ERROR",
"object": {
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "The resourceVersion for the provided watch is too old.",
"reason": "Expired",
"code": 410
}
}
```
version 616, is valid, it’s still 616 after …

feat: fix max CPU usage and memory leak

---

.circleci/config.yml
.github/CODEOWNERS
catalog-info.yaml

OI-471: Change repo ownership from orchestration-integrations to test-enrichment in `.github/CODEOWNERS`, `.circleci/config.yml` (snyk circleci context, secrets alerts channel) and `catalog-info.yaml` (github.com/team-slug, owner)
-- 
Generated by [Octopilot](https://github.com/dailymotion-oss/octopilot) [v1.12.15](https://github.com/dailymotion-oss/octopilot/releases/tag/v1.12.15) from https://github.com/snyk/prodsec-tools-v2

OI-471: Change repo ownership from orchestration-integrations to test-enrichment

---

.snyk
snyk-monitor/templates/deployment.yaml
test/integration/kubernetes.spec.ts
test/setup/deployers/helm.ts

- (n/a) Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
This PR fixes the Snyk Monitor pod `securityContext` block indentation in the Helm chart.
Tests have been updated to cover the use of the `podSecurityContext` and `securityContext` attributes in `values.yaml`.

fix: correct pod security context block indentation

---

.circleci/config.yml
.snyk
Dockerfile
Dockerfile.ubi9
jest-environment-fail-fast.ts
jest.config.js
jest.setup-after-env.js
package-lock.json
package.json
scripts/docker/build-image-ubi9.sh
scripts/docker/build-image.sh
test/unit/supervisor/pod-watch-handler-caches.spec.ts

- (n/a) Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
This PR resolves vulnerabilities in the Alpine and ubi9 flavours of the image.
ArtifactHub (powered by Trivy) previously reported quite a few vulnerabilities in the Alpine flavour; these are all resolved by this PR aside from two medium vulnerabilities introduced by the `request` dependency of `@kubernetes/client-node`, which will be replaced by `fetch` one they finish a migration. See [this doc](https://github.com/kubernetes-client/javascript/blob/master/FETCH_MIGRATION.md) for details.
- Resolving vulnerabilities in the `docker-credential-acr-env` binary required creating a fork.
- `Dockerfile`s have been aligned to be as similar as possible

fix: resolve vulnerabilities

---

Dockerfile
Dockerfile.ubi9

- (n/a) Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- (n/a) Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
This change ensures that the docker credential helper binaries listed below can be executed on the Alpine and UBI9 production images.
- `docker-credential-ecr-login`
- `docker-credential-acr-env`
Prior to this change, the binaries were built using the `golang:1.23` image. This would normally be okay, because Go by default produces statically linked binaries. _However_, the helpers both make use of the dependency `github.com/docker/docker-credential-helpers`, which forces CGO because of it's usage of system libraries to interact with local keychains. As a result, the binaries were dynamically linked, but without cross …

[OI-670] fix: use appropriate builder images for docker credential helpers

---

package-lock.json
package.json

Bumps `jsonpath-plus` to fix a vulnerability found in version 10.2.0.

fix: bump jsonpath-plus to 10.3.0

---

package-lock.json
package.json
src/scanner/images/credentials.ts

Migrates AWS SDK from v2 to v3
> Announcing end-of-support for AWS SDK for JavaScript v2 effective September 8, 2025
>
> In alignment with our [SDKs and Tools Maintenance Policy](https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html), [AWS SDK for JavaScript v2](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) will enter maintenance mode on September 8, 2024 and reach end-of-support on September 8, 2025.
>
> Existing applications that use AWS SDK for JavaScript v2 will continue to function as intended, unless there is a fundamental change to how an AWS service works. This is uncommon and would be broadly communicated if it happens. Between September 8, 2024 and end-of-support on September 8, 2025, the AWS SDK for JavaScript v2 will only receive …

feat: OI-798 migrate aws sdk from v2 to v3

---

package-lock.json
package.json

This PR updates and relocks NPM packages.
It is created by a recurring github action checking for outdated dependencies.
closes #1578 
closes #1560 
closes #1558

chore: Update and relock NPM packages

---

.circleci/config.yml
catalog-info.yaml

- Replace uses of `snyk/scan` with equivalent `prodsec/container_scan` calls
- Re-classify from `external-tooling` to `snyk-deployed-prod` as `kubernetes-monitor-deployer` is kicked off to do just that from `master` (see `deploy_to_prod.sh`)

chore: add prodsec container_scan
