snyk/kubernetes-monitor

.github/PULL_REQUEST_TEMPLATE.md

release notes are auto generated from fix/feat commits' titles.
once they are released, they may be edited, but let's try to be mindful of them before publishing them in the first place.

chore: enhance PR template with release notes reminder

---

.circleci/config.yml
test/helpers/kubectl.ts
test/setup/index.ts

store logs as CircleCI artifact after KinD integration test

chore: capture test logs and save as CircleCI artifacts

---

snyk-operator/README.md

Add more context around building and changing the Operator in the repository.
- [Jira ticket RUN-674](https://snyksec.atlassian.net/browse/RUN-674)

chore: update Operator README with build and change instructions

---

.circleci/config.yml

Revert a bad commit. This commit was used only to verify the CI changes in the feature branch.

chore: Revert "REMOVE ME! testing :)"

---

README.md

add Snyk's vuln badge to our main README. let's show off! 😬

chore: add Snyk's vuln badge to our main README

---

.circleci/config.yml

Makes it hard to read, and it looks like we are shouting.

chore: remove all caps from job names in CircleCI

---

src/scanner/images/skopeo.ts

today we use ```skopeo copy``` to create an archive file from an image.
if the destination already exists, ```skopeo copy``` fails.
this slightly collides with our retry mechanism for pulling and saving images in cases where the copy failed but the file was still created (maybe in a corrupt state).
in these cases, we will retry again and again but consistently fail.
this PR attempts to address it by deleting the destination file between attempts on failures.
https://snyk.slack.com/archives/CFSQFR0TH/p1585730273002100

fix: attempt to clean image archives if skopeo copy failed

---

.circleci/config.yml
scripts/docker/approve-image.sh
scripts/publish-gh-pages.sh
scripts/slack/notify-deploy.sh
scripts/slack/notify-failure-on-branch.sh
scripts/slack/notify-failure.sh
scripts/slack/notify-push.sh
scripts/slack/notify-success-no-publish.sh
scripts/slack/notify-success-no-release.sh
scripts/slack/notify_deploy.py
scripts/slack/notify_failure.py
scripts/slack/notify_failure_on_branch.py
scripts/slack/notify_push.py
scripts/slack/notify_success_no_publish.py
scripts/slack/notify_success_no_release.py

We wanted to clean up circleci scripts, rewriting them into python so they are environment agnostic.
- [Jira ticket RUN-840](https://snyksec.atlassian.net/browse/RUN-840)

chore: slack integration scripts rewritten to python

---

package.json
scripts/operator/package-operator.sh

chore: fix misspelling of YAML as YALM

---

src/state.ts

Minor code formatting changes.
- [Jira ticket RUN-886](https://snyksec.atlassian.net/browse/RUN-886?atlOrigin=eyJpIjoiMDNmNmEzYTRlN2JlNDE5ZDhjZTgwNjk4MzkzMjFmZmIiLCJwIjoiaiJ9)

chore: fix formatting in state.ts - organise imports

---

README.md
snyk-monitor/README.md

Reorganise the steps to make them clear to the user.
This PR is updating the README and snyk-monitor/README,  reorganising the steps when creating the snyk-monitor secret.
- [Jira ticket RUN-755](https://snyksec.atlassian.net/browse/RUN-755)

chore: Update README and snyk-monitor README

---

.circleci/config.yml
.circleci/config/@config.yml
.circleci/config/jobs/push_operator_to_community_operators.yml
scripts/slack/notify_success_operator_push.py

The commits to the community-operators are signed and use a user identity as required by the community guidelines.
- [Jira ticket RUN-989](https://snyksec.atlassian.net/browse/RUN-989)

chore: push new operators to community-operators repo

---

test/README.md

chore: add instructions for debugging with Tilt

---

test/fixtures/insecure-registries/push-dockerhub-image-to-local-registry.yaml
test/fixtures/insecure-registries/python-local-deployment.yaml
test/fixtures/insecure-registries/registries.conf
test/helpers/kubectl.ts
test/integration/kubernetes.test.ts
test/setup/index.ts
test/setup/platforms/cluster-config.yaml
test/setup/platforms/kind.ts

Adding missing local registry coverage.
Additionaly, the test exposed a bug in removeTagFromImage() func in src/scanner/images/index.ts, which chops off everything after ':' from the image name, so as a result we store a wrong image name.
- [Jira ticket RUN-980](https://snyksec.atlassian.net/browse/RUN-980)

test: Adding missing local registry coverage

---

.circleci/README.md

chore: fix typo

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/operator_upgrade_tests.yml

The latest version of operator-courier made it impossible to upload the operator, which broke our tests

test: fix operator-courier version 2.1.7

---

src/scanner/images/index.ts
test/unit/scanner/images.test.ts

improve image parts regex according to spec
Pay extra attention to the changes on tests because it modifies behaviour a bit
https://snyksec.atlassian.net/browse/RUN-1104

[RUN-1104] fix: improve image parts regex according to spec

---

Dockerfile

As part of the Red Hat certification process we need to use a Red Hat approved base image for our product.
- [Jira ticket RUN-828](https://snyksec.atlassian.net/browse/RUN-828)

feat: build snyk-monitor with a Red Hat UBI 8 base image

---

README.md
snyk-monitor/README.md

Include EULA disclaimer section on the bottom of the README file, on the Terms and conditions section.
The same disclaimer was included in the Snyk documentation on the bottom [here](https://support.snyk.io/hc/en-us/articles/360003916138-Kubernetes-integration-overview).
- [Jira ticket RUN-1112](https://snyksec.atlassian.net/browse/RUN-1112)

chore: improve README documentation

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml

fail the build if deployer returns an error
- [Jira ticket RUN-1105](https://snyksec.atlassian.net/browse/RUN-1105)

[RUN-1105] chore: fail the build if deployer returns an error

---

Dockerfile

update dockerfile so it works on Red Hat Build Server
- [Jira ticket RUN-1122](https://snyksec.atlassian.net/browse/RUN-1122)

[RUN-1122] fix: update dockerfile so it works on Red Hat Build Server

---

snyk-monitor/README.md
snyk-monitor/templates/clusterrole.yaml
snyk-monitor/templates/psp.yaml
snyk-monitor/templates/role.yaml
snyk-monitor/values.yaml
test/helpers/kubectl.ts
test/integration/kubernetes.test.ts
test/setup/deployers/helm.ts

Add PodSecurityPolicy support, based on a PR (https://github.com/snyk/kubernetes-monitor/pull/565) opened by @jalseth.
Thank you so much for this contribution :) 
https://kubernetes.io/docs/concepts/policy/pod-security-policy/

feat: Add support for PodSecurityPolicy

---

README.md
snyk-monitor-deployment.yaml
snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
src/common/logger.ts
test/integration/kubernetes.test.ts
test/setup/deployers/helm.ts

feat: control log level verbosity

---

test/integration/kubernetes.test.ts

Fix condition for executing test for LOG_LEVEL env existence

test: fix condition for executing test for LOG_LEVEL env existence

---

snyk-operator/build/Dockerfile

Upgrade Operator base image to fix vulnerabilities.
Resolves https://github.com/snyk/kubernetes-monitor/issues/574.

fix: upgrade Operator base image to fix vulnerabilities

---

src/scanner/images/index.ts
src/scanner/images/types.ts
src/scanner/index.ts
src/scanner/types.ts
src/transmitter/payload.ts
src/transmitter/types.ts
test/unit/scanner/images.test.ts
test/unit/transmitter-payload.test.ts

Pull image by SHA instead of the tag

feat: pull image by SHA instead of tag

---

src/scanner/index.ts
test/unit/scanner/index.test.ts

Fix pulling by digest from private registries

fix: pulling by digest from private registries

---

src/scanner/images/index.ts
src/scanner/images/types.ts
src/scanner/index.ts
src/scanner/types.ts
src/transmitter/payload.ts
src/transmitter/types.ts
test/unit/scanner/images.test.ts
test/unit/scanner/index.test.ts
test/unit/transmitter-payload.test.ts

Fallback to tag if digest missing

fix: fallback to tag if digest missing

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
scripts/slack/notify_failure.py
scripts/slack/notify_failure_on_branch.py

Add more details to Slack message on CircleCI Job failure

chore: add more details to Slack message on CircleCI Job failure

---

package-lock.json

Relock to update dependencies.

fix: relock to update dependencies

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/operator_upgrade_tests.yml
.circleci/config/jobs/push_operator_to_community_operators.yml
.circleci/config/jobs/push_operator_to_upstream_community_operators.yml

chore: fix Slack notifications on failed CI jobs

---

package-lock.json
package.json

Fixes transitive vuln https://snyk.io/vuln/SNYK-JS-Y18N-1021887 from snyk-config 3.1.1

fix: Update snyk-config version to remediate vuln

---

package-lock.json
package.json

Bring memory optimization from depGraph lib

feat: memory optimization from depGraph lib

---

.circleci/config.yml
.circleci/config/jobs/push_operator_to_community_operators.yml
.circleci/config/jobs/push_operator_to_upstream_community_operators.yml
scripts/operator/push-operator-to-snyk-upstream.sh

Fix operator build artifact folder location

chore: fix operator build artifact folder location

---

src/common/config.ts
src/common/logger.ts
src/common/process.ts
src/index.ts
src/scanner/images/credentials.ts
src/scanner/images/index.ts
src/scanner/images/skopeo.ts
src/scanner/index.ts
src/state.ts
src/supervisor/cluster.ts
src/supervisor/metadata-extractor.ts
src/supervisor/watchers/handlers/index.ts
src/supervisor/watchers/handlers/pod.ts
src/supervisor/watchers/handlers/workload.ts
src/supervisor/watchers/index.ts
src/supervisor/workload-reader.ts
src/transmitter/index.ts
src/transmitter/payload.ts
src/transmitter/proxy.ts
test/helpers/kubernetes-upstream.ts
test/integration/kubernetes.test.ts
test/system/kind.test.ts
test/unit/deployment-files.test.ts
test/unit/scanner/images.test.ts
test/unit/supervisor/pod-watch-handler-caches.test.ts
test/unit/supervisor/watchers.test.ts
test/unit/transmitter-payload.test.ts

Remove require statements from the code

chore: remove require, cos it's TypeScript and 2020 in the end of the day

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Enhance memory for in-container Node.js process

fix: memory enhancements for Node.js app

---

snyk-monitor/templates/deployment.yaml

feat: add quotes for .Values.skip_k8s_jobs, add tolerations

---

package-lock.json
package.json

In the latest release of the library, maintainers addressed the issue that might be related to the elevated errors we were seeing.
More info here https://github.com/kubernetes-client/javascript/issues/494

feat: upgrade kubernetes-client library

---

package-lock.json
package.json

feat: upgrade docker plugin to auto-detect Dockerfile instructions

---

package-lock.json
package.json

Update `@kubernetes/client-node` 3rd party dependency to fix connection leak.
Source
https://github.com/kubernetes-client/javascript/pull/576

fix: update k8s client to bring connection leak fix

---

snyk-monitor-deployment.yaml
snyk-monitor/values.yaml

Revert CPU limits to previous value

chore: revert CPU limits to previous value

---

Dockerfile

Update skopeo to fix vulnerabilities.
Before:
```shell
Tested 3 projects, 2 contained vulnerable paths.
...
✗ High severity vulnerability found in github.com/ulikunitz/xz
Description: Infinite Loop
Info: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMULIKUNITZXZ-598892
Introduced through: github.com/ulikunitz/xz@0.5.7
From: github.com/ulikunitz/xz@0.5.7
Fixed in: 0.5.8
✗ High severity vulnerability found in github.com/ulikunitz/xz
Description: Denial of Service (DoS)
Info: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMULIKUNITZXZ-607912
Introduced through: github.com/ulikunitz/xz@0.5.7
From: github.com/ulikunitz/xz@0.5.7
Fixed in: 0.5.8
```
After:
```
Tested 2 projects, no vulnerable paths were found.
```
Notice how Go is no longer detected unfortunately!

fix: update skopeo to fix vulnerabilities

---

package-lock.json
package.json

Update docker-plugin to improve detection of the OS of images.
https://github.com/snyk/snyk-docker-plugin/pull/331
https://snyk.zendesk.com/agent/tickets/9475

fix: update docker-plugin to improve detection of the OS of images

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml
scripts/operator/create_operator_bundle_and_index_and_push.py
scripts/operator/download_operator_package_manager.py

Fix Operator upgrade tests for OpenShift 4.6 and above.
- [Jira ticket RUN-1393](https://snyksec.atlassian.net/browse/RUN-1393)

chore: fix Operator upgrade tests for OpenShift 4.6 and above

---

package-lock.json
package.json

Update docker-plugin to add Yarn2 support and to return image ID with sha256 prefix.
Also relocking dependencies to get updates.

feat: Yarn2 support and returning image ID with sha256 prefix

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/config.yml

Add Github issue templates to have single view issues

chore: add github issues templates

---

package-lock.json
package.json

update snyk-docker-plugin  release to 4.20.3

Run 1464 go parser

---

.circleci/config.yml
.circleci/config/jobs/push_operator_to_community_operators.yml
.circleci/config/jobs/push_operator_to_upstream_community_operators.yml
scripts/slack/notify_success_operator_push.py

- [Slack: example missing data in notification](https://snyk.slack.com/archives/CLW30N31V/p1620230250072000)

chore: fix Slack notifications data by ensuring env vars are exported

---

src/transmitter/index.ts

Try to use `keepAlive` during `kubernetes-upstream` requests.
This PR avoids using `keepAlive` usage for instances that are using proxies.

feat: re-use sockets when sending data to kubernetes upstream

---

package-lock.json
package.json

Relock packages to update vulnerable packages

fix: relock packages to update vulnerable packages

---

package-lock.json
package.json

Remove unused devDependencies - sinon and @types/sinon

[RUN-1080] Remove unused devDependencies

---

src/index.ts
src/transmitter/index.ts
src/transmitter/payload.ts
src/transmitter/types.ts
test/system/kind.spec.ts

Sends cluster metadata on start up.

[RUN-1560] Send cluster metadata on start up

---

.dockerignore
README.md
scc.txt
snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
snyk-monitor/templates/networkpolicy.yaml
snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snyk-operator.v0.0.0.clusterserviceversion.yaml

Update main README with IBM Cloud Pak suggestions: description of CPU, memory, nodes, architecture, supported distributions, supported OCP version.

chore: update main README with IBM Cloud Pak suggestions

---

Dockerfile

Fixes several critical severity vulnerabilities in the base image.
**Before**
Tested 191 dependencies for known issues, found 23 issues.
**After**
✓ Tested 198 dependencies for known issues, no vulnerable paths found.

fix: update base image to resolve vulnerabilities

---

.commitlintrc.json
.dockerignore
package-lock.json
package.json

Using it only on the last 5 commits instead of the last 10 like in our other repos, because an invalid commit message was added recently and it would fail `commitlint`. Once we have enough commits written we can increase it to 10.

chore: add commitlint

---

.circleci/config.yml
.circleci/config/@config.yml
.circleci/config/jobs/sync_community_operators_with_snyk_fork.yml
scripts/operator/push-operator-to-snyk-upstream.sh

There was a race condition happening while the two Operator PR Jobs were running at the same time and trying to sync/update the Snyk fork of operator-framework/community-operators. This sync is now its own separate Job that runs before the two Operator PR Jobs.

[RUN-1589] Chore/sync community operators fork

---

.circleci/config.yml
.circleci/config/@config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/orbs/@azure-cli.yml
package.json
test/README.md
test/setup/index.ts
test/setup/platforms/aks.ts
test/setup/platforms/index.ts

test: add AKS integration test

---

snyk-monitor/README.md

README contained 2 sections - "Upgrade" and "Upgrading". I have merged them into one section.

chore: remove duplicate upgrade section

---

.circleci/config.yml
.circleci/config/commands/setup_node16.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
package-lock.json
package.json
src/common/config.ts
test/setup/index.ts
test/system/kind.spec.ts

Replace `uuid` package with native Node.js `crypto` package. Less 3rd party packages, less vulns.

fix: replace uuid package with native crypto

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/orbs/@aws-cli.yml
test/setup/platforms/eks.ts

Replace AWS CLI installation with CircleCI orb

test: replace AWS CLI installation with CircleCI orb

---

snyk-monitor/README.md

The excludedNamespaces set command was missing the "".

fix: update excludedNamespaces set command

---

package.json

`commitlint` to check all new commits

chore: commitlint to check all new commits

---

Dockerfile

fix: upgrade skopeo to fix vulnerabilities

---

Dockerfile
snyk-monitor/README.md

Add ecr-credential-helper to image
Related to #568

feat: add ecr-credential-helper to image

---

snyk-operator/build/Dockerfile

fix: upgrade helm-operator base image to resolve vulnerabilities

---

src/supervisor/kuberenetes-api-wrappers.ts

fix: remove variable in log

---

Dockerfile

Update base image to the latest version of `ubi8/ubi` images.

feat: update base image to the latest version

---

package-lock.json
package.json

upgrade Snyk Docker plugin to v4.26.1.

fix: upgrade snyk docker plugin

---

src/transmitter/index.ts

Renames homebase ref to kubernetes upstream

chore: rename homebase reference

---

package-lock.json
package.json

This PR bumps the version of the snyk-docker-plugin to make
use of the improved user instruction text through the newly added
installCommand property.
**See:** [[CAP-280](https://snyksec.atlassian.net/browse/CAP-280)]

fix: Improved user instructions

---

.circleci/config.yml
.circleci/config/@config.yml
.circleci/config/jobs/@jobs.yml

Run snyk test to check for vulns in the application and in the Docker image.
This will block builds only with `high` and above severity vulnerabilities.
Also run snyk test & snyk monitor before publishing the image.

chore: run snyk test in CI pipeline

---

package-lock.json
package.json

This PR update snyk-docker-plugin to v4.28.1.
- [Slack thread](https://snyk.slack.com/archives/C01EPSMGZML/p1639590254212300)

fix: Update snyk-docker-plugin to v4.28.1

---

package-lock.json
package.json

instead of 0
this also applies to --app-vulns with no --nested-jars-depth flag

feat: change default of nested jars unpacking to 1 #2480

---

package-lock.json
package.json

feat: bump sdp

---

snyk-monitor/values.yaml

Add tolerations to values.yaml
It is missing in the file but is used in the Deployment template
Original PR #976 by @BertelBB 🙏

chore: add tolerations to values.yaml

---

package-lock.json
package.json

Fix vuln in `snyk-docker-plugin`

fix: vuln in snyk-docker-plugin

---

package-lock.json
src/supervisor/metadata-extractor.ts
test/fixtures/sidecar-containers/deployment.yaml
test/unit/supervisor/metadata-extractor.spec.ts

Sanitize workload metadata before sending it to K-U

RUN-1968 fix: sanitize workload metadata

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Allow configuring deployment rollout strategy
Closes #1016

feat: allow configuring deployment rollout strategy

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml

chore: temporarily increase severity threshold for red hat images

---

.circleci/config.yml
.circleci/config/jobs/build_and_upload_operator.yml
package-lock.json

temporarily reset operator severity threshold as there is no fix available

fix: temporarily reset operator severity threshold

---

src/common/process.ts
src/supervisor/metadata-extractor.ts
src/supervisor/watchers/handlers/pod.ts
src/supervisor/workload-sanitization.ts

* capture error message from SKOPEO better
* add more logs to understand why some workloads don't produce scan result

RUN-2198 chore: add more logs for debug purpose

---

src/index.ts

Logs keep alive for debugging purposes.

feat: log use keep alive

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml
.circleci/config/jobs/push_operator_to_community_operators.yml
.circleci/config/jobs/push_operator_to_embedded_community_operators.yml

Fix flaky operator upgrade tests and wrong ubi image.

fix: fix flaky operator upgrade tests and wrong ubi image

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml

Set version when it is empty in operator tests.

fix: operator upgrade tests

---

package-lock.json
package.json

fix: update fs-extra

---

package-lock.json
package.json

Upgrade `snyk-docker-plugin` to its latest version, which supports PHP app scan for containers.

feat: php app scan

---

Dockerfile.ubi8

fix: update UBI8 base image

---

test/integration/kubernetes.spec.ts

chore: fix OS3 integration tests

---

.circleci/config/commands/setup_node16.yml
.circleci/config/jobs/@jobs.yml
test/fixtures/java-deployment.yaml
test/helpers/kubernetes-upstream.ts
test/system/kind.spec.ts

Fix integration & system test:
- Java image no longer exists => renamed to openjdk
- Change internal URL and rotated credentials
- remove Jest callbacks

chore: fix integration and system tests

---

.circleci/config.yml
.circleci/config/jobs/deploy_to_dev.yml
scripts/circleci-jobs/deploy_to_dev.sh

Change deploy to new internal deploy functionality

chore: change deploy to new internal deploy functionality

---

.circleci/config.yml
.circleci/config/jobs/deploy_to_dev.yml

Fix typo in path to deploy script

chore: fix typo in path to deploy script

---

scripts/circleci-jobs/deploy_to_dev.sh

Fix execution context path for deploy to dev

chore: fix execution context path for deploy to dev

---

scripts/circleci-jobs/deploy_to_dev.sh

Config git and add prod values file

chore: config git and add prod values file

---

scripts/circleci-jobs/deploy_to_dev.sh

Copy helm chart to deploy repo

chore: copy helm chart to deploy repo

---

.circleci/config.yml
.circleci/config/jobs/deploy_to_prod.yml
scripts/circleci-jobs/deploy_to_dev.sh
scripts/circleci-jobs/deploy_to_prod.sh

Approve deploy to prod in CircleCI

chore: approve deploy to prod in CircleCI

---

package-lock.json
package.json

Upgrade snyk-docker-plugin in order to get the latest fix and dependencies, including a fix in the docker-registry-v2-client.

fix: upgrade snyk-docker-plugin

---

src/scanner/images/index.ts

https://github.com/snyk/snyk-docker-plugin/releases

fix: upgrade docker plugin for Go improvements

---

test/setup/platforms/openshift4.ts

test: fix oc login command

---

test/helpers/kubectl.ts
test/setup/platforms/openshift4.ts

Patch os4 namespaces that are about to be deleted

test: patch os4 namespaces that are about to be deleted

---

package-lock.json
package.json

Bump `snyk-docker-plugin` with support for Python app scan

feat: python app scan for containers

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
.circleci/config/jobs/openshift3_integration_tests.yml
.circleci/config/jobs/openshift4_integration_tests.yml

Increase CI machines for integration tests

chore: increase CI machines for integration tests

---

test/helpers/kubectl.ts

Add debug data for os3 integration test

chore: add debug data for os3 integration test

---

package-lock.json
package.json
test/integration/kubernetes.spec.ts

Bumps the version of the docker-plugin to support trimmed, stripped and Cgo binaries.
See snyk-docker-plugin #447 for more info.

feat: container Go binary scan

---

test/unit/data-scraper/scrape-data.spec.ts
test/unit/transmitter-payload.spec.ts

chore: prepare for Jest update

---

package-lock.json
package.json

Improves the performance issues that cause errors while scanning python apps in some images

fix: improve python app scan performance

---

package-lock.json
package.json

See [snyk-docker-plugin #456](https://github.com/snyk/snyk-docker-plugin/pull/456) for more info.
Upgrade the snyk-docker-plugin.
See https://github.com/snyk/snyk-docker-plugin/pull/456 for more info.

fix: update snyk-docker-plugin to fix CGo binaries issue

---

scripts/circleci-jobs/deploy_to_dev.sh

Adapt to the new deployer version

chore: adapt to new deployer version

---

.circleci/config.yml
.circleci/config/jobs/operator_upgrade_tests.yml

test: fix upgrade test failures

---

test/setup/platforms/openshift4.ts

test: fix OpenShift 4 flakes

---

README.md
snyk-monitor/README.md

docs: consolidate READMEs and use Helm chart README for installation

---

.github/workflows/relock.yaml

Add auto relock PR github action

[RUN-2127] Auto relock PR github action

---

.snyk
package-lock.json
package.json

Bumps snyk-docker-plugin
Bumps snyk-docker-plugin
Bumps snyk-docker-plugin

fix: update snyk-docker-plugin

---

src/state.ts

fix: remove debug logging of cache

---

package-lock.json
package.json

Update lib Snyk Docker Plugin, so we can use the new fact ImageNames.

RUN-1928 chore: upgrade snyk docker plugin

---

.circleci/config.yml
.circleci/config/@config.yml
.github/workflows/release-notes.yaml

Add correct context to circle config to fix the deployment pipeline.

chore: add correct context to circle config

---

.circleci/config.yml
.circleci/config/@config.yml

Add the circle context to two more steps that are required.

chore: add circle context to all required steps

---

.github/CODEOWNERS

Rename team from Runtime to Container Integration

chore: rename team

---

package-lock.json
package.json

- container python dist-packages support
- https://github.com/snyk/snyk-docker-plugin/pull/476

fix: container python dist-packages support

---

snyk-operator-certified/Dockerfile
snyk-operator/build/Dockerfile

update helm operator image version to fix vulnerabilities.

fix: update helm operator image version

---

Dockerfile.ubi8
snyk-operator-certified/Dockerfile
snyk-operator/build/Dockerfile

Update RHEL UBI8 image to latest version to resolve vulns found in older image versions.

fix: update rhel ubi image

---

package.json
test/system/kind.spec.ts

Update system tests to check for auth header existence
In order to make sure expected nock requests are fulfilled, this PR also adds waiting mechanism for expected http calls.

[CIT-112] test: update system tests to check for auth header existence

---

src/transmitter/index.ts

Log version to help with debugging.

chore: log version

---

scripts/circleci-jobs/deploy_to_dev.sh

Reduce logging in our deployed monitor.

chore: reduce logging

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/build_and_upload_operator.yml
.circleci/config/jobs/build_image.yml
.circleci/config/jobs/integration_tests_operator_on_k8s.yml
.circleci/config/jobs/openshift4_integration_tests.yml
.circleci/config/jobs/operator_upgrade_tests.yml
.circleci/config/jobs/push_operator_to_community_operators.yml
.circleci/config/jobs/push_operator_to_embedded_community_operators.yml
Dockerfile.ubi9
scripts/docker/approve-image.sh
scripts/docker/build-image-ubi9.sh
scripts/operator/main.py
snyk-operator-certified/bundle/manifests/snyk-monitor.clusterserviceversion.yaml
snyk-operator-certified/config/manifests/bases/snyk-monitor.clusterserviceversion.yaml
snyk-operator-certified/helm-charts/snyk-monitor/values.yaml

Upgrade RHEL UBI image version to ubi9.2.

chore: upgrade RHEL image to ubi9

---

src/supervisor/kuberenetes-api-wrappers.ts
src/supervisor/types.ts
src/supervisor/watchers/handlers/error.ts
src/supervisor/watchers/handlers/index.ts
src/supervisor/watchers/handlers/namespace.ts
src/supervisor/watchers/handlers/pagination.ts
src/supervisor/watchers/types.ts

Retry on "too many requests" from Google Kubernetes Engine

fix: retry on "too many requests" from Google Kubernetes Engine

---

.circleci/config.yml
.circleci/config/@config.yml

Skip integration test to enable pipeline
Close #1329 #1330

chore: disable integration tests

---

Dockerfile.ubi9
package-lock.json
package.json

fix: update deps

---

Dockerfile.ubi9

Remove echo args which were added for debugging purposes.

chore: remove echo args

---

.circleci/config.yml
.circleci/config/jobs/@jobs.yml
.circleci/config/jobs/build_image.yml
.circleci/config/orbs/@prodsec.yml
.gitleaksignore
.pre-commit-config.yaml
.snyk

Adds secret scanning detection to pre-commit and CI

Chore secrets scanning

---

package-lock.json
package.json

Contains an important fix for Debian source package lookups.

fix: bump snyk-docker-plugin

---

.github/workflows/relock.yaml

See internal slack discussion: https://snyk.slack.com/archives/C07N668DA/p1693564826434639

chore: use "fix" commit type when upgrading dependencies

---

.github/workflows/relock.yaml

Also updates `package.json` with the upgraded packages. See https://github.com/snyk/docker-deps/pull/1366 for an example.
This makes it very easy to read which direct dependencies changed when reviewing the PRs created by the `Update and relock NPM packages` job. 
close #1360 

chore: save packages after updating

---

package-lock.json
package.json

Attempt to fix the conflict between staging and master.

fix: manually bring changes from staging to master

---

test/unit/snyk-dep-graph.spec.ts

Adds percent-encoded plus sign in purl version tests

fix: add percent-encoded plus sign in purl version tests

---

package-lock.json
package.json

updates library to a version that downloads layers directly to disk instead of memory. resolves high memory consumption and NodeJS buffer errors while trying to allocate 4GB+ buffers.
SUP-2357

feat: large layer support

---

snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml
src/common/config.ts
src/common/types.ts
src/data-scraper/index.ts
src/healthcheck.ts
src/index.ts
src/transmitter/payload.ts
src/transmitter/types.ts
test/unit/data-scraper/scrape-data.spec.ts

Migrates to Sysdig v2 EVE API.

feat: use Sysdig EVE public API [CIT-704]

---

src/data-scraper/scraping-v1.ts
src/healthcheck.ts
src/index.ts
test/unit/data-scraper/scrape-data.spec.ts

The check if sysdig is configured or not is currently wrong.
Additionally, using this PR to move V1 to its own file in order to prepare for a future cleanup.

fix: correctly check if sysdig is enabled

---

scripts/circleci-jobs/deploy_to_prod.sh

Update deploy script to search for `Approve prod deployment` string, which is the new name of the approval job in the pipeline.

fix: update deploy script to search for correct approval job name

---

snyk-monitor/README.md
snyk-monitor/templates/deployment.yaml
src/common/config.ts
src/common/types.ts
src/data-scraper/index.ts
src/healthcheck.ts
src/index.ts
test/unit/data-scraper/scrape-data.spec.ts

Renames sysdig region to endpoint as per feedback from Sysdig.

feat: rename region to endpoint

---

scripts/circleci-jobs/prepare_to_deploy.sh

Fixes an internal scripts for deployment introduced in #1453.
- n/a Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- n/a Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)

fix: repair file copying in internal deploy process [OI-100]

---

package-lock.json
package.json

Bump `snyk-docker-plugin` version to 6.10.2 to contain the fix of supporting large/complex container project files files to fix an issue for customers.
For more details : https://github.com/snyk/snyk-docker-plugin/pull/569

fix: support monitoring larger/complex container projects

---

.circleci/config.yml

Add quality gate to PR_TO_STAGING and results upload to MERGE_TO_MASTER

feat: add quality gates

---

package-lock.json
package.json

This PR updates and relocks NPM packages.
It is created by a recurring github action checking for outdated dependencies.

chore: Update and relock NPM packages

---

scripts/circleci-jobs/prepare_to_deploy.sh

Team rename

---

.prettierignore
.snyk

Add temp ignores for two recent vulns that have no patch available yet.
N/A
N/A

chore: add temp ignores

---

Dockerfile.ubi9

feat: bump to ubi 9.3

---

.snyk
Dockerfile.ubi9
package-lock.json
package.json

Bump to `ubi9.4` base image.
N/A
N/A

Fix/bump ubi9.4

---

.snyk
package-lock.json
package.json

chore : bump snyk-docker-plugin to the latest version

---

package-lock.json
package.json

This reverts commit 79492934f51cdd1d1a53b60d659ae0f41066313e.
The bump will be merged again after following the breaking change process.
More information [on this slack thread](https://snyk.slack.com/archives/C06KUU9FXUZ/p1727423810592899).

Revert "chore : bump snyk-docker-plugin to the latest version"

---

snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

See Original PR here: #1519.
Cherry-picked here to target `staging` branch. Reworded commit messages for commitlint.

feat: helm add pod security context value

---

scripts/circleci-jobs/prepare_to_deploy.sh

chore: update team slug

---

Dockerfile.ubi9

fix: upgrade to ubi9.5

---

package-lock.json
package.json

Updates @kubernetes/client-node to v0.22.3 to resolve vuln.

fix: update k8s client

---

Dockerfile
Dockerfile.ubi9
snyk-monitor/templates/deployment.yaml
snyk-monitor/values.yaml

Allows Deployment labels to be configurable.

feat: allow deployment labels to be configured

---

.circleci/config.yml
scripts/circleci-jobs/deploy_to_prod.sh

use environment variable from context

chore: use environment variable from context

---

.circleci/config.yml
scripts/circleci-jobs/setup-integration-tests.py

- n/a Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- n/a Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
Change name of envvar, which is now referenced from a context.

chore: reference envvar from context

---

Dockerfile
Dockerfile.ubi9

[COIN-906] Upgrade acr creds helper

---

.circleci/config.yml

fix: semantic release

---

.snyk
package-lock.json

chore: merge pr fix

---

README.md

fix: force rebuild
